language: cpp
sudo: false
dist: trusty

compiler: 
  - gcc
  - clang

script:
  - mkdir build-$CC
  - cd build-$CC
  - cmake -DCMAKE_C_COMPILER=`which $CC` -DCMAKE_CXX_COMPILER=`which $CXX` ..
  - make -j8
  - make test
