language: cpp
sudo: false
dist: trusty

compiler: 
  - gcc
#  Remove clang for now as the default clang++-3.5 segfaults on Caliper code :-/
#  - clang

script:
  - mkdir build-${CC}
  - cd build-${CC}
  - cmake -DCMAKE_C_COMPILER=`which $CC` -DCMAKE_CXX_COMPILER=`which $CXX` ..
  - make -j4
  - make test
