//Generated by translate.py

#include <gotcha/gotcha.h>
#include <silo.h>
#include <stdio.h>
#include "dissectio.h"
#include <caliper/cali.h>
#include "gotcha_silo.h"

#define NFUNCS 10

static DBfile * (*WRAP_DBCreateReal) (char const *name, int mode, int targ, char const *info, int dbtype);
static DBfile * dissectio_DBCreateReal (char const *name, int mode, int targ, char const *info, int dbtype){
	cali_begin_string_byname("io.func","DBCreateReal");
	cali_end_byname("io.func");
	return WRAP_DBCreateReal(name, mode, targ, info, dbtype);
}

static DBfile * (*WRAP_DBOpenReal) (char const *name, int dbtype, int mode);
static DBfile * dissectio_DBOpenReal (char const *name, int dbtype, int mode){
	cali_begin_string_byname("io.func","DBOpenReal");
	cali_end_byname("io.func");
	return WRAP_DBOpenReal(name, dbtype, mode);
}

static int (*WRAP_DBWrite) (DBfile * dbfile, char const * varname, void const * var, int const * dims, int ndims,int datatype);
static int dissectio_DBWrite (DBfile * dbfile, char const * varname, void const * var, int const * dims, int ndims,int datatype){
	cali_begin_string_byname("io.func","DBWrite");
	cali_end_byname("io.func");
	return WRAP_DBWrite(dbfile, varname, var, dims, ndims, datatype);
}

static int (*WRAP_DBPutUcdvar) (DBfile * dbfile, char const * name, char const * meshname, int nvars, char const * const * varnames, DBVCP2_t vars, int nels, DBVCP2_t mixvars, int mixlen, int datatype, int centering, DBoptlist const * optlist);
static int dissectio_DBPutUcdvar (DBfile * dbfile, char const * name, char const * meshname, int nvars, char const * const * varnames, DBVCP2_t vars, int nels, DBVCP2_t mixvars, int mixlen, int datatype, int centering, DBoptlist const * optlist){
	cali_begin_string_byname("io.func","DBPutUcdvar");
	cali_end_byname("io.func");
	return WRAP_DBPutUcdvar(dbfile, name, meshname, nvars, varnames, vars, nels, mixvars, mixlen, datatype, centering, optlist);
}

static int (*WRAP_DBPutUcdvar1) (DBfile * dbfile, char const * name, char const * meshname, DBVCP1_t var, int nels, DBVCP1_t mixvar, int mixlen, int datatype, int centering, DBoptlist const * optlist);
static int dissectio_DBPutUcdvar1 (DBfile * dbfile, char const * name, char const * meshname, DBVCP1_t var, int nels, DBVCP1_t mixvar, int mixlen, int datatype, int centering, DBoptlist const * optlist){
	cali_begin_string_byname("io.func","DBPutUcdvar1");
	cali_end_byname("io.func");
	return WRAP_DBPutUcdvar1(dbfile, name, meshname, var, nels, mixvar, mixlen, datatype, centering, optlist);
}

static int (*WRAP_DBPutUcdmesh) (DBfile * dbfile, char const * name, int ndims, char const * const * coordnames, DBVCP2_t coords, int nnodes, int nzones, char const * zonel_name, char const * facel_name, int datatype, DBoptlist const * optlist);
static int dissectio_DBPutUcdmesh (DBfile * dbfile, char const * name, int ndims, char const * const * coordnames, DBVCP2_t coords, int nnodes, int nzones, char const * zonel_name, char const * facel_name, int datatype, DBoptlist const * optlist){
	cali_begin_string_byname("io.func","DBPutUcdmesh");
	cali_end_byname("io.func");
	return WRAP_DBPutUcdmesh(dbfile, name, ndims, coordnames, coords, nnodes, nzones, zonel_name, facel_name, datatype, optlist);
}

static int (*WRAP_DBPutMultimesh) (DBfile * dbfile, char const * name, int nmesh, char const * const * meshnames, int const * meshtypes, DBoptlist const * optlist);
static int dissectio_DBPutMultimesh (DBfile * dbfile, char const * name, int nmesh, char const * const * meshnames, int const * meshtypes, DBoptlist const * optlist){
	cali_begin_string_byname("io.func","DBPutMultimesh");
	cali_end_byname("io.func");
	return WRAP_DBPutMultimesh(dbfile, name, nmesh, meshnames, meshtypes, optlist);
}

static int (*WRAP_DBPutMultivar) (DBfile * dbfile, char const * name, int nvar, char const * const * varnames, int	const * vartypes, DBoptlist const * optlist);
static int dissectio_DBPutMultivar (DBfile * dbfile, char const * name, int nvar, char const * const * varnames, int	const * vartypes, DBoptlist const * optlist){
	cali_begin_string_byname("io.func","DBPutMultivar");
	cali_end_byname("io.func");
	return WRAP_DBPutMultivar(dbfile, name, nvar, varnames, vartypes, optlist);
}

static int (*WRAP_DBPutZonelist2) (DBfile * dbfile, char const * name, int nzones, int ndims, int const * nodelist, int lnodelist, int origin, int lo_offset, int hi_offset, int const * shapetype, int const * shapesize, int const * shapecnt, int nshapes, DBoptlist const * optlist);
static int dissectio_DBPutZonelist2 (DBfile * dbfile, char const * name, int nzones, int ndims, int const * nodelist, int lnodelist, int origin, int lo_offset, int hi_offset, int const * shapetype, int const * shapesize, int const * shapecnt, int nshapes, DBoptlist const * optlist){
	cali_begin_string_byname("io.func","DBPutZonelist2");
	cali_end_byname("io.func");
	return WRAP_DBPutZonelist2(dbfile, name, nzones, ndims, nodelist, lnodelist, origin, lo_offset, hi_offset, shapetype, shapesize, shapecnt, nshapes, optlist);
}

static int (*WRAP_DBClose) (DBfile * dbfile);
static int dissectio_DBClose (DBfile * dbfile){
	cali_begin_string_byname("io.func","DBClose");
	cali_end_byname("io.func");
	return WRAP_DBClose(dbfile);
}


struct gotcha_binding_t wrap_silo [] = {
	{ "DBCreateReal", dissectio_DBCreateReal, &WRAP_DBCreateReal },
	{ "DBOpenReal", dissectio_DBOpenReal, &WRAP_DBOpenReal },
	{ "DBWrite", dissectio_DBWrite, &WRAP_DBWrite },
	{ "DBPutUcdvar", dissectio_DBPutUcdvar, &WRAP_DBPutUcdvar },
	{ "DBPutUcdvar1", dissectio_DBPutUcdvar1, &WRAP_DBPutUcdvar1 },
	{ "DBPutUcdmesh", dissectio_DBPutUcdmesh, &WRAP_DBPutUcdmesh },
	{ "DBPutMultimesh", dissectio_DBPutMultimesh, &WRAP_DBPutMultimesh },
	{ "DBPutMultivar", dissectio_DBPutMultivar, &WRAP_DBPutMultivar },
	{ "DBPutZonelist2", dissectio_DBPutZonelist2, &WRAP_DBPutZonelist2 },
	{ "DBClose", dissectio_DBClose, &WRAP_DBClose },
};

void init_gotcha_silo () {
	gotcha_wrap(wrap_silo, NFUNCS, "dissectio");
}
