//Generated by translate.py
#include "gotcha_posix.h"
#include <gotcha/gotcha.h>
#include <sys/stat.h>
#include <dirent.h>
#include <stdint.h>
#include <sys/types.h>
#ifndef HAVE_OFF64_T
typedef int64_t off64_t;
#endif
#define __USE_LARGEFILE64
#include <stdio.h>
#include "dissectio.h"
#include <caliper/Annotation.h>

#define NFUNCS 56

static int (*WRAP_fflush) (FILE *stream);
static int dissectio_fflush (FILE *stream){
		cali::Annotation io_annot("io");
		io_annot.set("fflush");
		io_annot.end();
	return WRAP_fflush(stream);
}

static int (*WRAP_creat) (const char *path, mode_t mode);
static int dissectio_creat (const char *path, mode_t mode){
		cali::Annotation io_annot("io");
		io_annot.set("creat");
		io_annot.end();
	return WRAP_creat(path, mode);
}

static int (*WRAP_creat64) (const char *path, mode_t mode);
static int dissectio_creat64 (const char *path, mode_t mode){
		cali::Annotation io_annot("io");
		io_annot.set("creat64");
		io_annot.end();
	return WRAP_creat64(path, mode);
}

static int (*WRAP_open) (const char *path, int flags, ...);
static int dissectio_open (const char *path, int flags, ...){
		cali::Annotation io_annot("io");
		io_annot.set("open");
		io_annot.end();
	return WRAP_open(path, flags);
}

static int (*WRAP_open64) (const char *path, int flags, ...);
static int dissectio_open64 (const char *path, int flags, ...){
		cali::Annotation io_annot("io");
		io_annot.set("open64");
		io_annot.end();
	return WRAP_open64(path, flags);
}

static int (*WRAP_close) (int fd);
static int dissectio_close (int fd){
		cali::Annotation io_annot("io");
		io_annot.set("close");
		io_annot.end();
	return WRAP_close(fd);
}

static ssize_t (*WRAP_write) (int fd, const void *buf, size_t count);
static ssize_t dissectio_write (int fd, const void *buf, size_t count){
		cali::Annotation io_annot("io");
		io_annot.set("write");
		io_annot.end();
	return WRAP_write(fd, buf, count);
}

static ssize_t (*WRAP_read) (int fd, void *buf, size_t count);
static ssize_t dissectio_read (int fd, void *buf, size_t count){
		cali::Annotation io_annot("io");
		io_annot.set("read");
		io_annot.end();
	return WRAP_read(fd, buf, count);
}

static off_t (*WRAP_lseek) (int fd, off_t offset, int whence);
static off_t dissectio_lseek (int fd, off_t offset, int whence){
		cali::Annotation io_annot("io");
		io_annot.set("lseek");
		io_annot.end();
	return WRAP_lseek(fd, offset, whence);
}

static off64_t (*WRAP_lseek64) (int fd, off64_t offset, int whence);
static off64_t dissectio_lseek64 (int fd, off64_t offset, int whence){
		cali::Annotation io_annot("io");
		io_annot.set("lseek64");
		io_annot.end();
	return WRAP_lseek64(fd, offset, whence);
}

static ssize_t (*WRAP_pread) (int fd, void *buf, size_t count, off_t offset);
static ssize_t dissectio_pread (int fd, void *buf, size_t count, off_t offset){
		cali::Annotation io_annot("io");
		io_annot.set("pread");
		io_annot.end();
	return WRAP_pread(fd, buf, count, offset);
}

static ssize_t (*WRAP_pread64) (int fd, void *buf, size_t count, off64_t offset);
static ssize_t dissectio_pread64 (int fd, void *buf, size_t count, off64_t offset){
		cali::Annotation io_annot("io");
		io_annot.set("pread64");
		io_annot.end();
	return WRAP_pread64(fd, buf, count, offset);
}

static ssize_t (*WRAP_pwrite) (int fd, const void *buf, size_t count, off_t offset);
static ssize_t dissectio_pwrite (int fd, const void *buf, size_t count, off_t offset){
		cali::Annotation io_annot("io");
		io_annot.set("pwrite");
		io_annot.end();
	return WRAP_pwrite(fd, buf, count, offset);
}

static ssize_t (*WRAP_pwrite64) (int fd, const void *buf, size_t count, off64_t offset);
static ssize_t dissectio_pwrite64 (int fd, const void *buf, size_t count, off64_t offset){
		cali::Annotation io_annot("io");
		io_annot.set("pwrite64");
		io_annot.end();
	return WRAP_pwrite64(fd, buf, count, offset);
}

static ssize_t (*WRAP_readv) (int fd, const struct iovec *iov, int iovcnt);
static ssize_t dissectio_readv (int fd, const struct iovec *iov, int iovcnt){
		cali::Annotation io_annot("io");
		io_annot.set("readv");
		io_annot.end();
	return WRAP_readv(fd, iov, iovcnt);
}

static ssize_t (*WRAP_writev) (int fd, const struct iovec *iov, int iovcnt);
static ssize_t dissectio_writev (int fd, const struct iovec *iov, int iovcnt){
		cali::Annotation io_annot("io");
		io_annot.set("writev");
		io_annot.end();
	return WRAP_writev(fd, iov, iovcnt);
}

static int (*WRAP_remove) (const char *filename);
static int dissectio_remove (const char *filename){
		cali::Annotation io_annot("io");
		io_annot.set("remove");
		io_annot.end();
	return WRAP_remove(filename);
}

static int (*WRAP_unlink) (const char *filename);
static int dissectio_unlink (const char *filename){
		cali::Annotation io_annot("io");
		io_annot.set("unlink");
		io_annot.end();
	return WRAP_unlink(filename);
}

static int (*WRAP_madvise) (void *addr, size_t length, int advice);
static int dissectio_madvise (void *addr, size_t length, int advice){
		cali::Annotation io_annot("io");
		io_annot.set("madvise");
		io_annot.end();
	return WRAP_madvise(addr, length, advice);
}

static DIR* (*WRAP_opendir) (const char *dirname);
static DIR* dissectio_opendir (const char *dirname){
		cali::Annotation io_annot("io");
		io_annot.set("opendir");
		io_annot.end();
	return WRAP_opendir(dirname);
}

static DIR* (*WRAP_fdopendir) (int fd);
static DIR* dissectio_fdopendir (int fd){
		cali::Annotation io_annot("io");
		io_annot.set("fdopendir");
		io_annot.end();
	return WRAP_fdopendir(fd);
}

static struct dirent64* (*WRAP_readdir64) (DIR *dirstream);
static struct dirent64* dissectio_readdir64 (DIR *dirstream){
		cali::Annotation io_annot("io");
		io_annot.set("readdir64");
		io_annot.end();
	return WRAP_readdir64(dirstream);
}

static struct dirent* (*WRAP_readdir) (DIR *dirstream);
static struct dirent* dissectio_readdir (DIR *dirstream){
		cali::Annotation io_annot("io");
		io_annot.set("readdir");
		io_annot.end();
	return WRAP_readdir(dirstream);
}

static int (*WRAP_dirfd) (DIR *dirstream);
static int dissectio_dirfd (DIR *dirstream){
		cali::Annotation io_annot("io");
		io_annot.set("dirfd");
		io_annot.end();
	return WRAP_dirfd(dirstream);
}

static char* (*WRAP_mktemp) (char *template);
static char* dissectio_mktemp (char *template){
		cali::Annotation io_annot("io");
		io_annot.set("mktemp");
		io_annot.end();
	return WRAP_mktemp(template);
}

static int (*WRAP_mkstemp) (char *template);
static int dissectio_mkstemp (char *template){
		cali::Annotation io_annot("io");
		io_annot.set("mkstemp");
		io_annot.end();
	return WRAP_mkstemp(template);
}

static char* (*WRAP_mkdtemp) (char *template);
static char* dissectio_mkdtemp (char *template){
		cali::Annotation io_annot("io");
		io_annot.set("mkdtemp");
		io_annot.end();
	return WRAP_mkdtemp(template);
}

static int (*WRAP_rmdir) (const char *filename);
static int dissectio_rmdir (const char *filename){
		cali::Annotation io_annot("io");
		io_annot.set("rmdir");
		io_annot.end();
	return WRAP_rmdir(filename);
}

static int (*WRAP_truncate) (const char *filename, off_t length);
static int dissectio_truncate (const char *filename, off_t length){
		cali::Annotation io_annot("io");
		io_annot.set("truncate");
		io_annot.end();
	return WRAP_truncate(filename, length);
}

static long int (*WRAP_telldir) (DIR *dirstream);
static long int dissectio_telldir (DIR *dirstream){
		cali::Annotation io_annot("io");
		io_annot.set("telldir");
		io_annot.end();
	return WRAP_telldir(dirstream);
}

static int (*WRAP_ftruncate) (int fd, off_t length);
static int dissectio_ftruncate (int fd, off_t length){
		cali::Annotation io_annot("io");
		io_annot.set("ftruncate");
		io_annot.end();
	return WRAP_ftruncate(fd, length);
}

static long int (*WRAP_ftell) (FILE *stream);
static long int dissectio_ftell (FILE *stream){
		cali::Annotation io_annot("io");
		io_annot.set("ftell");
		io_annot.end();
	return WRAP_ftell(stream);
}

static off_t (*WRAP_ftello) (FILE *stream);
static off_t dissectio_ftello (FILE *stream){
		cali::Annotation io_annot("io");
		io_annot.set("ftello");
		io_annot.end();
	return WRAP_ftello(stream);
}

static off64_t (*WRAP_ftello64) (FILE *stream);
static off64_t dissectio_ftello64 (FILE *stream){
		cali::Annotation io_annot("io");
		io_annot.set("ftello64");
		io_annot.end();
	return WRAP_ftello64(stream);
}

static int (*WRAP_closedir) (DIR *dirstream);
static int dissectio_closedir (DIR *dirstream){
		cali::Annotation io_annot("io");
		io_annot.set("closedir");
		io_annot.end();
	return WRAP_closedir(dirstream);
}

static int (*WRAP_fgetpos) (FILE *stream, fpos_t *position);
static int dissectio_fgetpos (FILE *stream, fpos_t *position){
		cali::Annotation io_annot("io");
		io_annot.set("fgetpos");
		io_annot.end();
	return WRAP_fgetpos(stream, position);
}

static int (*WRAP_fgetpos64) (FILE *stream, fpos64_t *position);
static int dissectio_fgetpos64 (FILE *stream, fpos64_t *position){
		cali::Annotation io_annot("io");
		io_annot.set("fgetpos64");
		io_annot.end();
	return WRAP_fgetpos64(stream, position);
}

static int (*WRAP_fsetpos) (FILE *stream, const fpos_t *position);
static int dissectio_fsetpos (FILE *stream, const fpos_t *position){
		cali::Annotation io_annot("io");
		io_annot.set("fsetpos");
		io_annot.end();
	return WRAP_fsetpos(stream, position);
}

static int (*WRAP_fsetpos64) (FILE *stream, const fpos64_t *position);
static int dissectio_fsetpos64 (FILE *stream, const fpos64_t *position){
		cali::Annotation io_annot("io");
		io_annot.set("fsetpos64");
		io_annot.end();
	return WRAP_fsetpos64(stream, position);
}

static int (*WRAP_fflush_unlocked) (FILE *stream);
static int dissectio_fflush_unlocked (FILE *stream){
		cali::Annotation io_annot("io");
		io_annot.set("fflush_unlocked");
		io_annot.end();
	return WRAP_fflush_unlocked(stream);
}

static int (*WRAP___fxstat) (int vers, int fd, struct stat *buf);
static int dissectio___fxstat (int vers, int fd, struct stat *buf){
		cali::Annotation io_annot("io");
		io_annot.set("__fxstat");
		io_annot.end();
	return WRAP___fxstat(vers, fd, buf);
}

static int (*WRAP___fxstat64) (int vers, int fd, struct stat64 *buf);
static int dissectio___fxstat64 (int vers, int fd, struct stat64 *buf){
		cali::Annotation io_annot("io");
		io_annot.set("__fxstat64");
		io_annot.end();
	return WRAP___fxstat64(vers, fd, buf);
}

static int (*WRAP___lxstat) (int vers, const char *path, struct stat *buf);
static int dissectio___lxstat (int vers, const char *path, struct stat *buf){
		cali::Annotation io_annot("io");
		io_annot.set("__lxstat");
		io_annot.end();
	return WRAP___lxstat(vers, path, buf);
}

static int (*WRAP___lxstat64) (int vers, const char *path, struct stat64 *buf);
static int dissectio___lxstat64 (int vers, const char *path, struct stat64 *buf){
		cali::Annotation io_annot("io");
		io_annot.set("__lxstat64");
		io_annot.end();
	return WRAP___lxstat64(vers, path, buf);
}

static int (*WRAP___xstat) (int vers, const char *path, struct stat *buf);
static int dissectio___xstat (int vers, const char *path, struct stat *buf){
		cali::Annotation io_annot("io");
		io_annot.set("__xstat");
		io_annot.end();
	return WRAP___xstat(vers, path, buf);
}

static int (*WRAP___xstat64) (int vers, const char *path, struct stat64 *buf);
static int dissectio___xstat64 (int vers, const char *path, struct stat64 *buf){
		cali::Annotation io_annot("io");
		io_annot.set("__xstat64");
		io_annot.end();
	return WRAP___xstat64(vers, path, buf);
}

static void * (*WRAP_mmap) (void *addr, size_t length, int prot, int flags, int fd, off_t offset);
static void * dissectio_mmap (void *addr, size_t length, int prot, int flags, int fd, off_t offset){
		cali::Annotation io_annot("io");
		io_annot.set("mmap");
		io_annot.end();
	return WRAP_mmap(addr, length, prot, flags, fd, offset);
}

static void * (*WRAP_mmap64) (void *addr, size_t length, int prot, int flags, int fd, off64_t offset);
static void * dissectio_mmap64 (void *addr, size_t length, int prot, int flags, int fd, off64_t offset){
		cali::Annotation io_annot("io");
		io_annot.set("mmap64");
		io_annot.end();
	return WRAP_mmap64(addr, length, prot, flags, fd, offset);
}

static FILE * (*WRAP_fopen) (const char *path, const char *mode);
static FILE * dissectio_fopen (const char *path, const char *mode){
		cali::Annotation io_annot("io");
		io_annot.set("fopen");
		io_annot.end();
	return WRAP_fopen(path, mode);
}

static FILE * (*WRAP_fopen64) (const char *path, const char *mode);
static FILE * dissectio_fopen64 (const char *path, const char *mode){
		cali::Annotation io_annot("io");
		io_annot.set("fopen64");
		io_annot.end();
	return WRAP_fopen64(path, mode);
}

static int (*WRAP_fclose) (FILE * fp);
static int dissectio_fclose (FILE * fp){
		cali::Annotation io_annot("io");
		io_annot.set("fclose");
		io_annot.end();
	return WRAP_fclose(fp);
}

static size_t (*WRAP_fread) (void *ptr, size_t size, size_t nmemb, FILE *stream);
static size_t dissectio_fread (void *ptr, size_t size, size_t nmemb, FILE *stream){
		cali::Annotation io_annot("io");
		io_annot.set("fread");
		io_annot.end();
	return WRAP_fread(ptr, size, nmemb, stream);
}

static size_t (*WRAP_fwrite) (const void *ptr, size_t size, size_t nmemb, FILE *stream);
static size_t dissectio_fwrite (const void *ptr, size_t size, size_t nmemb, FILE *stream){
		cali::Annotation io_annot("io");
		io_annot.set("fwrite");
		io_annot.end();
	return WRAP_fwrite(ptr, size, nmemb, stream);
}

static int (*WRAP_fseek) (FILE * stream, long offset, int whence);
static int dissectio_fseek (FILE * stream, long offset, int whence){
		cali::Annotation io_annot("io");
		io_annot.set("fseek");
		io_annot.end();
	return WRAP_fseek(stream, offset, whence);
}

static int (*WRAP_fsync) (int fd);
static int dissectio_fsync (int fd){
		cali::Annotation io_annot("io");
		io_annot.set("fsync");
		io_annot.end();
	return WRAP_fsync(fd);
}

static int (*WRAP_fdatasync) (int fd);
static int dissectio_fdatasync (int fd){
		cali::Annotation io_annot("io");
		io_annot.set("fdatasync");
		io_annot.end();
	return WRAP_fdatasync(fd);
}


struct gotcha_binding_t wrap_posix [] = {
	{ "fflush", dissectio_fflush, &WRAP_fflush },
	{ "creat", dissectio_creat, &WRAP_creat },
	{ "creat64", dissectio_creat64, &WRAP_creat64 },
	{ "open", dissectio_open, &WRAP_open },
	{ "open64", dissectio_open64, &WRAP_open64 },
	{ "close", dissectio_close, &WRAP_close },
	{ "write", dissectio_write, &WRAP_write },
	{ "read", dissectio_read, &WRAP_read },
	{ "lseek", dissectio_lseek, &WRAP_lseek },
	{ "lseek64", dissectio_lseek64, &WRAP_lseek64 },
	{ "pread", dissectio_pread, &WRAP_pread },
	{ "pread64", dissectio_pread64, &WRAP_pread64 },
	{ "pwrite", dissectio_pwrite, &WRAP_pwrite },
	{ "pwrite64", dissectio_pwrite64, &WRAP_pwrite64 },
	{ "readv", dissectio_readv, &WRAP_readv },
	{ "writev", dissectio_writev, &WRAP_writev },
	{ "remove", dissectio_remove, &WRAP_remove },
	{ "unlink", dissectio_unlink, &WRAP_unlink },
	{ "madvise", dissectio_madvise, &WRAP_madvise },
	{ "opendir", dissectio_opendir, &WRAP_opendir },
	{ "fdopendir", dissectio_fdopendir, &WRAP_fdopendir },
	{ "readdir64", dissectio_readdir64, &WRAP_readdir64 },
	{ "readdir", dissectio_readdir, &WRAP_readdir },
	{ "dirfd", dissectio_dirfd, &WRAP_dirfd },
	{ "mktemp", dissectio_mktemp, &WRAP_mktemp },
	{ "mkstemp", dissectio_mkstemp, &WRAP_mkstemp },
	{ "mkdtemp", dissectio_mkdtemp, &WRAP_mkdtemp },
	{ "rmdir", dissectio_rmdir, &WRAP_rmdir },
	{ "truncate", dissectio_truncate, &WRAP_truncate },
	{ "telldir", dissectio_telldir, &WRAP_telldir },
	{ "ftruncate", dissectio_ftruncate, &WRAP_ftruncate },
	{ "ftell", dissectio_ftell, &WRAP_ftell },
	{ "ftello", dissectio_ftello, &WRAP_ftello },
	{ "ftello64", dissectio_ftello64, &WRAP_ftello64 },
	{ "closedir", dissectio_closedir, &WRAP_closedir },
	{ "fgetpos", dissectio_fgetpos, &WRAP_fgetpos },
	{ "fgetpos64", dissectio_fgetpos64, &WRAP_fgetpos64 },
	{ "fsetpos", dissectio_fsetpos, &WRAP_fsetpos },
	{ "fsetpos64", dissectio_fsetpos64, &WRAP_fsetpos64 },
	{ "fflush_unlocked", dissectio_fflush_unlocked, &WRAP_fflush_unlocked },
	{ "__fxstat", dissectio___fxstat, &WRAP___fxstat },
	{ "__fxstat64", dissectio___fxstat64, &WRAP___fxstat64 },
	{ "__lxstat", dissectio___lxstat, &WRAP___lxstat },
	{ "__lxstat64", dissectio___lxstat64, &WRAP___lxstat64 },
	{ "__xstat", dissectio___xstat, &WRAP___xstat },
	{ "__xstat64", dissectio___xstat64, &WRAP___xstat64 },
	{ "mmap", dissectio_mmap, &WRAP_mmap },
	{ "mmap64", dissectio_mmap64, &WRAP_mmap64 },
	{ "fopen", dissectio_fopen, &WRAP_fopen },
	{ "fopen64", dissectio_fopen64, &WRAP_fopen64 },
	{ "fclose", dissectio_fclose, &WRAP_fclose },
	{ "fread", dissectio_fread, &WRAP_fread },
	{ "fwrite", dissectio_fwrite, &WRAP_fwrite },
	{ "fseek", dissectio_fseek, &WRAP_fseek },
	{ "fsync", dissectio_fsync, &WRAP_fsync },
	{ "fdatasync", dissectio_fdatasync, &WRAP_fdatasync },
};

void init_gotcha_posix () {
	gotcha_wrap(wrap_posix, NFUNCS, "dissectio");
}
