//Generated by translate.py

#include "gotcha_all_silo.h"
#include <gotcha/gotcha.h>
#include <all.h>
#include <stdio.h>
#include "dissectio.h"
#include <caliper/Annotation.h>

#define NFUNCS 237

static void (*WRAP_DBShowErrors) (int a, DBErrFunc_t b);
static void dissectio_DBShowErrors (int a, DBErrFunc_t b){
		cali::Annotation io_annot("io");
		io_annot.set("DBShowErrors");
		io_annot.end();
	return WRAP_DBShowErrors(a, b);
}

static char const * (*WRAP_DBErrString) ();
static char const * dissectio_DBErrString (){
		cali::Annotation io_annot("io");
		io_annot.set("DBErrString");
		io_annot.end();
	return WRAP_DBErrString();
}

static char const * (*WRAP_DBErrFuncname) ();
static char const * dissectio_DBErrFuncname (){
		cali::Annotation io_annot("io");
		io_annot.set("DBErrFuncname");
		io_annot.end();
	return WRAP_DBErrFuncname();
}

static DBErrFunc_t (*WRAP_DBErrfunc) ();
static DBErrFunc_t dissectio_DBErrfunc (){
		cali::Annotation io_annot("io");
		io_annot.set("DBErrfunc");
		io_annot.end();
	return WRAP_DBErrfunc();
}

static int (*WRAP_DBErrno) ();
static int dissectio_DBErrno (){
		cali::Annotation io_annot("io");
		io_annot.set("DBErrno");
		io_annot.end();
	return WRAP_DBErrno();
}

static int (*WRAP_DBErrlvl) ();
static int dissectio_DBErrlvl (){
		cali::Annotation io_annot("io");
		io_annot.set("DBErrlvl");
		io_annot.end();
	return WRAP_DBErrlvl();
}

static unsigned long long (*WRAP_DBSetDataReadMask2) (unsigned long long a);
static unsigned long long dissectio_DBSetDataReadMask2 (unsigned long long a){
		cali::Annotation io_annot("io");
		io_annot.set("DBSetDataReadMask2");
		io_annot.end();
	return WRAP_DBSetDataReadMask2(a);
}

static unsigned long long (*WRAP_DBGetDataReadMask2) ();
static unsigned long long dissectio_DBGetDataReadMask2 (){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetDataReadMask2");
		io_annot.end();
	return WRAP_DBGetDataReadMask2();
}

static char * (*WRAP_DBGetDatatypeString) (int datatype);
static char * dissectio_DBGetDatatypeString (int datatype){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetDatatypeString");
		io_annot.end();
	return WRAP_DBGetDatatypeString(datatype);
}

static int (*WRAP_DBSetAllowOverwrites) (int allow);
static int dissectio_DBSetAllowOverwrites (int allow){
		cali::Annotation io_annot("io");
		io_annot.set("DBSetAllowOverwrites");
		io_annot.end();
	return WRAP_DBSetAllowOverwrites(allow);
}

static int (*WRAP_DBGetAllowOverwrites) ();
static int dissectio_DBGetAllowOverwrites (){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetAllowOverwrites");
		io_annot.end();
	return WRAP_DBGetAllowOverwrites();
}

static int (*WRAP_DBSetAllowEmptyObjects) (int allow);
static int dissectio_DBSetAllowEmptyObjects (int allow){
		cali::Annotation io_annot("io");
		io_annot.set("DBSetAllowEmptyObjects");
		io_annot.end();
	return WRAP_DBSetAllowEmptyObjects(allow);
}

static int (*WRAP_DBGetAllowEmptyObjects) ();
static int dissectio_DBGetAllowEmptyObjects (){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetAllowEmptyObjects");
		io_annot.end();
	return WRAP_DBGetAllowEmptyObjects();
}

static int (*WRAP_DBSetEnableChecksums) (int enable);
static int dissectio_DBSetEnableChecksums (int enable){
		cali::Annotation io_annot("io");
		io_annot.set("DBSetEnableChecksums");
		io_annot.end();
	return WRAP_DBSetEnableChecksums(enable);
}

static int (*WRAP_DBGetEnableChecksums) ();
static int dissectio_DBGetEnableChecksums (){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetEnableChecksums");
		io_annot.end();
	return WRAP_DBGetEnableChecksums();
}

static void (*WRAP_DBSetCompression) (char const * b);
static void dissectio_DBSetCompression (char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBSetCompression");
		io_annot.end();
	return WRAP_DBSetCompression(b);
}

static char const * (*WRAP_DBGetCompression) ();
static char const * dissectio_DBGetCompression (){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetCompression");
		io_annot.end();
	return WRAP_DBGetCompression();
}

static int (*WRAP_DBSetFriendlyHDF5Names) (int enable);
static int dissectio_DBSetFriendlyHDF5Names (int enable){
		cali::Annotation io_annot("io");
		io_annot.set("DBSetFriendlyHDF5Names");
		io_annot.end();
	return WRAP_DBSetFriendlyHDF5Names(enable);
}

static int (*WRAP_DBGetFriendlyHDF5Names) ();
static int dissectio_DBGetFriendlyHDF5Names (){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetFriendlyHDF5Names");
		io_annot.end();
	return WRAP_DBGetFriendlyHDF5Names();
}

static int (*WRAP_DBSetDeprecateWarnings) (int max);
static int dissectio_DBSetDeprecateWarnings (int max){
		cali::Annotation io_annot("io");
		io_annot.set("DBSetDeprecateWarnings");
		io_annot.end();
	return WRAP_DBSetDeprecateWarnings(max);
}

static int (*WRAP_DBGetDeprecateWarnings) ();
static int dissectio_DBGetDeprecateWarnings (){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetDeprecateWarnings");
		io_annot.end();
	return WRAP_DBGetDeprecateWarnings();
}

static int const * (*WRAP_DBSetUnknownDriverPriorities) (int const *a);
static int const * dissectio_DBSetUnknownDriverPriorities (int const *a){
		cali::Annotation io_annot("io");
		io_annot.set("DBSetUnknownDriverPriorities");
		io_annot.end();
	return WRAP_DBSetUnknownDriverPriorities(a);
}

static int const * (*WRAP_DBGetUnknownDriverPriorities) ();
static int const * dissectio_DBGetUnknownDriverPriorities (){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetUnknownDriverPriorities");
		io_annot.end();
	return WRAP_DBGetUnknownDriverPriorities();
}

static int (*WRAP_DBRegisterFileOptionsSet) (DBoptlist const *opts);
static int dissectio_DBRegisterFileOptionsSet (DBoptlist const *opts){
		cali::Annotation io_annot("io");
		io_annot.set("DBRegisterFileOptionsSet");
		io_annot.end();
	return WRAP_DBRegisterFileOptionsSet(opts);
}

static int (*WRAP_DBUnregisterFileOptionsSet) (int opts_set_id);
static int dissectio_DBUnregisterFileOptionsSet (int opts_set_id){
		cali::Annotation io_annot("io");
		io_annot.set("DBUnregisterFileOptionsSet");
		io_annot.end();
	return WRAP_DBUnregisterFileOptionsSet(opts_set_id);
}

static void (*WRAP_DBUnregisterAllFileOptionsSets) ();
static void dissectio_DBUnregisterAllFileOptionsSets (){
		cali::Annotation io_annot("io");
		io_annot.set("DBUnregisterAllFileOptionsSets");
		io_annot.end();
	return WRAP_DBUnregisterAllFileOptionsSets();
}

static char const * (*WRAP_DBVersion) ();
static char const * dissectio_DBVersion (){
		cali::Annotation io_annot("io");
		io_annot.set("DBVersion");
		io_annot.end();
	return WRAP_DBVersion();
}

static int (*WRAP_DBVersionDigits) (int *Maj, int *Min, int *Pat, int *Pre);
static int dissectio_DBVersionDigits (int *Maj, int *Min, int *Pat, int *Pre){
		cali::Annotation io_annot("io");
		io_annot.set("DBVersionDigits");
		io_annot.end();
	return WRAP_DBVersionDigits(Maj, Min, Pat, Pre);
}

static int (*WRAP_DBVersionGE) (int Maj, int Min, int Pat);
static int dissectio_DBVersionGE (int Maj, int Min, int Pat){
		cali::Annotation io_annot("io");
		io_annot.set("DBVersionGE");
		io_annot.end();
	return WRAP_DBVersionGE(Maj, Min, Pat);
}

static int (*WRAP_DBVariableNameValid) (char const *s);
static int dissectio_DBVariableNameValid (char const *s){
		cali::Annotation io_annot("io");
		io_annot.set("DBVariableNameValid");
		io_annot.end();
	return WRAP_DBVariableNameValid(s);
}

static int (*WRAP_DBForceSingle) (int a);
static int dissectio_DBForceSingle (int a){
		cali::Annotation io_annot("io");
		io_annot.set("DBForceSingle");
		io_annot.end();
	return WRAP_DBForceSingle(a);
}

static DBfile * (*WRAP_DBOpenReal) (char const *name, int dbtype, int mode);
static DBfile * dissectio_DBOpenReal (char const *name, int dbtype, int mode){
		cali::Annotation io_annot("io");
		io_annot.set("DBOpenReal");
		io_annot.end();
	return WRAP_DBOpenReal(name, dbtype, mode);
}

static DBfile * (*WRAP_DBCreateReal) (char const *name, int mode, int targ, char const *info, int dbtype);
static DBfile * dissectio_DBCreateReal (char const *name, int mode, int targ, char const *info, int dbtype){
		cali::Annotation io_annot("io");
		io_annot.set("DBCreateReal");
		io_annot.end();
	return WRAP_DBCreateReal(name, mode, targ, info, dbtype);
}

static int (*WRAP_DBInqFileReal) (char const *name);
static int dissectio_DBInqFileReal (char const *name){
		cali::Annotation io_annot("io");
		io_annot.set("DBInqFileReal");
		io_annot.end();
	return WRAP_DBInqFileReal(name);
}

static int (*WRAP_DBClose) (DBfile * a);
static int dissectio_DBClose (DBfile * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBClose");
		io_annot.end();
	return WRAP_DBClose(a);
}

static DBtoc * (*WRAP_DBGetToc) (DBfile * b);
static DBtoc * dissectio_DBGetToc (DBfile * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetToc");
		io_annot.end();
	return WRAP_DBGetToc(b);
}

static int (*WRAP_DBNewToc) (DBfile * c);
static int dissectio_DBNewToc (DBfile * c){
		cali::Annotation io_annot("io");
		io_annot.set("DBNewToc");
		io_annot.end();
	return WRAP_DBNewToc(c);
}

static void * (*WRAP_DBGrabDriver) (DBfile * d);
static void * dissectio_DBGrabDriver (DBfile * d){
		cali::Annotation io_annot("io");
		io_annot.set("DBGrabDriver");
		io_annot.end();
	return WRAP_DBGrabDriver(d);
}

static int (*WRAP_DBUngrabDriver) (DBfile * e, void const * f);
static int dissectio_DBUngrabDriver (DBfile * e, void const * f){
		cali::Annotation io_annot("io");
		io_annot.set("DBUngrabDriver");
		io_annot.end();
	return WRAP_DBUngrabDriver(e, f);
}

static int (*WRAP_DBGetDriverType) (DBfile const * g);
static int dissectio_DBGetDriverType (DBfile const * g){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetDriverType");
		io_annot.end();
	return WRAP_DBGetDriverType(g);
}

static int (*WRAP_DBGetDriverTypeFromPath) (char const * h);
static int dissectio_DBGetDriverTypeFromPath (char const * h){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetDriverTypeFromPath");
		io_annot.end();
	return WRAP_DBGetDriverTypeFromPath(h);
}

static int (*WRAP_DBVersionGEFileVersion) (DBfile const *dbfile);
static int dissectio_DBVersionGEFileVersion (DBfile const *dbfile){
		cali::Annotation io_annot("io");
		io_annot.set("DBVersionGEFileVersion");
		io_annot.end();
	return WRAP_DBVersionGEFileVersion(dbfile);
}

static char const * (*WRAP_DBFileVersion) (DBfile const *dbfile);
static char const * dissectio_DBFileVersion (DBfile const *dbfile){
		cali::Annotation io_annot("io");
		io_annot.set("DBFileVersion");
		io_annot.end();
	return WRAP_DBFileVersion(dbfile);
}

static int (*WRAP_DBFileVersionDigits) (DBfile const *dbfile, int *Maj, int *Min, int *Pat, int *Pre);
static int dissectio_DBFileVersionDigits (DBfile const *dbfile, int *Maj, int *Min, int *Pat, int *Pre){
		cali::Annotation io_annot("io");
		io_annot.set("DBFileVersionDigits");
		io_annot.end();
	return WRAP_DBFileVersionDigits(dbfile, Maj, Min, Pat, Pre);
}

static int (*WRAP_DBFileVersionGE) (DBfile const *dbfile, int Maj, int Min, int Pat);
static int dissectio_DBFileVersionGE (DBfile const *dbfile, int Maj, int Min, int Pat){
		cali::Annotation io_annot("io");
		io_annot.set("DBFileVersionGE");
		io_annot.end();
	return WRAP_DBFileVersionGE(dbfile, Maj, Min, Pat);
}

static int (*WRAP_DBGetDir) (DBfile * a, char * b);
static int dissectio_DBGetDir (DBfile * a, char * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetDir");
		io_annot.end();
	return WRAP_DBGetDir(a, b);
}

static int (*WRAP_DBSetDir) (DBfile * a, char const * b);
static int dissectio_DBSetDir (DBfile * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBSetDir");
		io_annot.end();
	return WRAP_DBSetDir(a, b);
}

static int (*WRAP_DBMkDir) (DBfile * a, char const * b);
static int dissectio_DBMkDir (DBfile * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBMkDir");
		io_annot.end();
	return WRAP_DBMkDir(a, b);
}

static int (*WRAP_DBCpDir) (DBfile *dbfile, char const *srcDir, DBfile *dstFile, char const *dstDir);
static int dissectio_DBCpDir (DBfile *dbfile, char const *srcDir, DBfile *dstFile, char const *dstDir){
		cali::Annotation io_annot("io");
		io_annot.set("DBCpDir");
		io_annot.end();
	return WRAP_DBCpDir(dbfile, srcDir, dstFile, dstDir);
}

static int (*WRAP_DBGuessHasFriendlyHDF5Names) (DBfile *f);
static int dissectio_DBGuessHasFriendlyHDF5Names (DBfile *f){
		cali::Annotation io_annot("io");
		io_annot.set("DBGuessHasFriendlyHDF5Names");
		io_annot.end();
	return WRAP_DBGuessHasFriendlyHDF5Names(f);
}

static int (*WRAP_DBInqVarExists) (DBfile * a, char const * b);
static int dissectio_DBInqVarExists (DBfile * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBInqVarExists");
		io_annot.end();
	return WRAP_DBInqVarExists(a, b);
}

static int (*WRAP_DBUninstall) (DBfile * a);
static int dissectio_DBUninstall (DBfile * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBUninstall");
		io_annot.end();
	return WRAP_DBUninstall(a);
}

static int (*WRAP_DBFreeCompressionResources) (DBfile *dbfile, char const *meshname);
static int dissectio_DBFreeCompressionResources (DBfile *dbfile, char const *meshname){
		cali::Annotation io_annot("io");
		io_annot.set("DBFreeCompressionResources");
		io_annot.end();
	return WRAP_DBFreeCompressionResources(dbfile, meshname);
}

static int (*WRAP_DBSortObjectsByOffset) (DBfile * f, int nobjs, char const * const *obj_names, int *ranks);
static int dissectio_DBSortObjectsByOffset (DBfile * f, int nobjs, char const * const *obj_names, int *ranks){
		cali::Annotation io_annot("io");
		io_annot.set("DBSortObjectsByOffset");
		io_annot.end();
	return WRAP_DBSortObjectsByOffset(f, nobjs, obj_names, ranks);
}

static int (*WRAP_DBFilters) (DBfile * a, FILE * b);
static int dissectio_DBFilters (DBfile * a, FILE * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBFilters");
		io_annot.end();
	return WRAP_DBFilters(a, b);
}

static int (*WRAP_DBInqFileHasObjects) (DBfile * a);
static int dissectio_DBInqFileHasObjects (DBfile * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBInqFileHasObjects");
		io_annot.end();
	return WRAP_DBInqFileHasObjects(a);
}

static DBcompoundarray * (*WRAP_DBAllocCompoundarray) ();
static DBcompoundarray * dissectio_DBAllocCompoundarray (){
		cali::Annotation io_annot("io");
		io_annot.set("DBAllocCompoundarray");
		io_annot.end();
	return WRAP_DBAllocCompoundarray();
}

static DBcurve * (*WRAP_DBAllocCurve) ();
static DBcurve * dissectio_DBAllocCurve (){
		cali::Annotation io_annot("io");
		io_annot.set("DBAllocCurve");
		io_annot.end();
	return WRAP_DBAllocCurve();
}

static DBdefvars * (*WRAP_DBAllocDefvars) (int a);
static DBdefvars * dissectio_DBAllocDefvars (int a){
		cali::Annotation io_annot("io");
		io_annot.set("DBAllocDefvars");
		io_annot.end();
	return WRAP_DBAllocDefvars(a);
}

static DBmultimesh * (*WRAP_DBAllocMultimesh) (int a);
static DBmultimesh * dissectio_DBAllocMultimesh (int a){
		cali::Annotation io_annot("io");
		io_annot.set("DBAllocMultimesh");
		io_annot.end();
	return WRAP_DBAllocMultimesh(a);
}

static DBmultimeshadj * (*WRAP_DBAllocMultimeshadj) (int a);
static DBmultimeshadj * dissectio_DBAllocMultimeshadj (int a){
		cali::Annotation io_annot("io");
		io_annot.set("DBAllocMultimeshadj");
		io_annot.end();
	return WRAP_DBAllocMultimeshadj(a);
}

static DBmultivar * (*WRAP_DBAllocMultivar) (int a);
static DBmultivar * dissectio_DBAllocMultivar (int a){
		cali::Annotation io_annot("io");
		io_annot.set("DBAllocMultivar");
		io_annot.end();
	return WRAP_DBAllocMultivar(a);
}

static DBmultimat * (*WRAP_DBAllocMultimat) (int a);
static DBmultimat * dissectio_DBAllocMultimat (int a){
		cali::Annotation io_annot("io");
		io_annot.set("DBAllocMultimat");
		io_annot.end();
	return WRAP_DBAllocMultimat(a);
}

static DBmultimatspecies * (*WRAP_DBAllocMultimatspecies) (int a);
static DBmultimatspecies * dissectio_DBAllocMultimatspecies (int a){
		cali::Annotation io_annot("io");
		io_annot.set("DBAllocMultimatspecies");
		io_annot.end();
	return WRAP_DBAllocMultimatspecies(a);
}

static DBcsgmesh * (*WRAP_DBAllocCsgmesh) ();
static DBcsgmesh * dissectio_DBAllocCsgmesh (){
		cali::Annotation io_annot("io");
		io_annot.set("DBAllocCsgmesh");
		io_annot.end();
	return WRAP_DBAllocCsgmesh();
}

static DBquadmesh * (*WRAP_DBAllocQuadmesh) ();
static DBquadmesh * dissectio_DBAllocQuadmesh (){
		cali::Annotation io_annot("io");
		io_annot.set("DBAllocQuadmesh");
		io_annot.end();
	return WRAP_DBAllocQuadmesh();
}

static DBpointmesh * (*WRAP_DBAllocPointmesh) ();
static DBpointmesh * dissectio_DBAllocPointmesh (){
		cali::Annotation io_annot("io");
		io_annot.set("DBAllocPointmesh");
		io_annot.end();
	return WRAP_DBAllocPointmesh();
}

static DBmeshvar * (*WRAP_DBAllocMeshvar) ();
static DBmeshvar * dissectio_DBAllocMeshvar (){
		cali::Annotation io_annot("io");
		io_annot.set("DBAllocMeshvar");
		io_annot.end();
	return WRAP_DBAllocMeshvar();
}

static DBucdmesh * (*WRAP_DBAllocUcdmesh) ();
static DBucdmesh * dissectio_DBAllocUcdmesh (){
		cali::Annotation io_annot("io");
		io_annot.set("DBAllocUcdmesh");
		io_annot.end();
	return WRAP_DBAllocUcdmesh();
}

static DBcsgvar * (*WRAP_DBAllocCsgvar) ();
static DBcsgvar * dissectio_DBAllocCsgvar (){
		cali::Annotation io_annot("io");
		io_annot.set("DBAllocCsgvar");
		io_annot.end();
	return WRAP_DBAllocCsgvar();
}

static DBquadvar * (*WRAP_DBAllocQuadvar) ();
static DBquadvar * dissectio_DBAllocQuadvar (){
		cali::Annotation io_annot("io");
		io_annot.set("DBAllocQuadvar");
		io_annot.end();
	return WRAP_DBAllocQuadvar();
}

static DBucdvar * (*WRAP_DBAllocUcdvar) ();
static DBucdvar * dissectio_DBAllocUcdvar (){
		cali::Annotation io_annot("io");
		io_annot.set("DBAllocUcdvar");
		io_annot.end();
	return WRAP_DBAllocUcdvar();
}

static DBzonelist * (*WRAP_DBAllocZonelist) ();
static DBzonelist * dissectio_DBAllocZonelist (){
		cali::Annotation io_annot("io");
		io_annot.set("DBAllocZonelist");
		io_annot.end();
	return WRAP_DBAllocZonelist();
}

static DBphzonelist * (*WRAP_DBAllocPHZonelist) ();
static DBphzonelist * dissectio_DBAllocPHZonelist (){
		cali::Annotation io_annot("io");
		io_annot.set("DBAllocPHZonelist");
		io_annot.end();
	return WRAP_DBAllocPHZonelist();
}

static DBcsgzonelist * (*WRAP_DBAllocCSGZonelist) ();
static DBcsgzonelist * dissectio_DBAllocCSGZonelist (){
		cali::Annotation io_annot("io");
		io_annot.set("DBAllocCSGZonelist");
		io_annot.end();
	return WRAP_DBAllocCSGZonelist();
}

static DBedgelist * (*WRAP_DBAllocEdgelist) ();
static DBedgelist * dissectio_DBAllocEdgelist (){
		cali::Annotation io_annot("io");
		io_annot.set("DBAllocEdgelist");
		io_annot.end();
	return WRAP_DBAllocEdgelist();
}

static DBfacelist * (*WRAP_DBAllocFacelist) ();
static DBfacelist * dissectio_DBAllocFacelist (){
		cali::Annotation io_annot("io");
		io_annot.set("DBAllocFacelist");
		io_annot.end();
	return WRAP_DBAllocFacelist();
}

static DBmaterial * (*WRAP_DBAllocMaterial) ();
static DBmaterial * dissectio_DBAllocMaterial (){
		cali::Annotation io_annot("io");
		io_annot.set("DBAllocMaterial");
		io_annot.end();
	return WRAP_DBAllocMaterial();
}

static DBmatspecies * (*WRAP_DBAllocMatspecies) ();
static DBmatspecies * dissectio_DBAllocMatspecies (){
		cali::Annotation io_annot("io");
		io_annot.set("DBAllocMatspecies");
		io_annot.end();
	return WRAP_DBAllocMatspecies();
}

static DBnamescheme * (*WRAP_DBAllocNamescheme) ();
static DBnamescheme * dissectio_DBAllocNamescheme (){
		cali::Annotation io_annot("io");
		io_annot.set("DBAllocNamescheme");
		io_annot.end();
	return WRAP_DBAllocNamescheme();
}

static DBgroupelmap * (*WRAP_DBAllocGroupelmap) (int a, DBdatatype b);
static DBgroupelmap * dissectio_DBAllocGroupelmap (int a, DBdatatype b){
		cali::Annotation io_annot("io");
		io_annot.set("DBAllocGroupelmap");
		io_annot.end();
	return WRAP_DBAllocGroupelmap(a, b);
}

static void (*WRAP_DBFreeMatspecies) (DBmatspecies * a);
static void dissectio_DBFreeMatspecies (DBmatspecies * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBFreeMatspecies");
		io_annot.end();
	return WRAP_DBFreeMatspecies(a);
}

static void (*WRAP_DBFreeMaterial) (DBmaterial * a);
static void dissectio_DBFreeMaterial (DBmaterial * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBFreeMaterial");
		io_annot.end();
	return WRAP_DBFreeMaterial(a);
}

static void (*WRAP_DBFreeFacelist) (DBfacelist * a);
static void dissectio_DBFreeFacelist (DBfacelist * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBFreeFacelist");
		io_annot.end();
	return WRAP_DBFreeFacelist(a);
}

static void (*WRAP_DBFreeEdgelist) (DBedgelist * a);
static void dissectio_DBFreeEdgelist (DBedgelist * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBFreeEdgelist");
		io_annot.end();
	return WRAP_DBFreeEdgelist(a);
}

static void (*WRAP_DBFreeZonelist) (DBzonelist * a);
static void dissectio_DBFreeZonelist (DBzonelist * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBFreeZonelist");
		io_annot.end();
	return WRAP_DBFreeZonelist(a);
}

static void (*WRAP_DBFreePHZonelist) (DBphzonelist * a);
static void dissectio_DBFreePHZonelist (DBphzonelist * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBFreePHZonelist");
		io_annot.end();
	return WRAP_DBFreePHZonelist(a);
}

static void (*WRAP_DBFreeCSGZonelist) (DBcsgzonelist * a);
static void dissectio_DBFreeCSGZonelist (DBcsgzonelist * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBFreeCSGZonelist");
		io_annot.end();
	return WRAP_DBFreeCSGZonelist(a);
}

static void (*WRAP_DBResetUcdvar) (DBucdvar * a);
static void dissectio_DBResetUcdvar (DBucdvar * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBResetUcdvar");
		io_annot.end();
	return WRAP_DBResetUcdvar(a);
}

static void (*WRAP_DBFreeUcdvar) (DBucdvar * a);
static void dissectio_DBFreeUcdvar (DBucdvar * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBFreeUcdvar");
		io_annot.end();
	return WRAP_DBFreeUcdvar(a);
}

static void (*WRAP_DBResetQuadvar) (DBquadvar * a);
static void dissectio_DBResetQuadvar (DBquadvar * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBResetQuadvar");
		io_annot.end();
	return WRAP_DBResetQuadvar(a);
}

static void (*WRAP_DBFreeCsgvar) (DBcsgvar * a);
static void dissectio_DBFreeCsgvar (DBcsgvar * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBFreeCsgvar");
		io_annot.end();
	return WRAP_DBFreeCsgvar(a);
}

static void (*WRAP_DBFreeQuadvar) (DBquadvar * a);
static void dissectio_DBFreeQuadvar (DBquadvar * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBFreeQuadvar");
		io_annot.end();
	return WRAP_DBFreeQuadvar(a);
}

static void (*WRAP_DBFreeUcdmesh) (DBucdmesh * a);
static void dissectio_DBFreeUcdmesh (DBucdmesh * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBFreeUcdmesh");
		io_annot.end();
	return WRAP_DBFreeUcdmesh(a);
}

static void (*WRAP_DBFreeMeshvar) (DBmeshvar * a);
static void dissectio_DBFreeMeshvar (DBmeshvar * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBFreeMeshvar");
		io_annot.end();
	return WRAP_DBFreeMeshvar(a);
}

static void (*WRAP_DBFreePointvar) (DBpointvar * a);
static void dissectio_DBFreePointvar (DBpointvar * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBFreePointvar");
		io_annot.end();
	return WRAP_DBFreePointvar(a);
}

static void (*WRAP_DBFreePointmesh) (DBpointmesh * a);
static void dissectio_DBFreePointmesh (DBpointmesh * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBFreePointmesh");
		io_annot.end();
	return WRAP_DBFreePointmesh(a);
}

static void (*WRAP_DBFreeQuadmesh) (DBquadmesh * a);
static void dissectio_DBFreeQuadmesh (DBquadmesh * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBFreeQuadmesh");
		io_annot.end();
	return WRAP_DBFreeQuadmesh(a);
}

static void (*WRAP_DBFreeCsgmesh) (DBcsgmesh * a);
static void dissectio_DBFreeCsgmesh (DBcsgmesh * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBFreeCsgmesh");
		io_annot.end();
	return WRAP_DBFreeCsgmesh(a);
}

static void (*WRAP_DBFreeDefvars) (DBdefvars* a);
static void dissectio_DBFreeDefvars (DBdefvars* a){
		cali::Annotation io_annot("io");
		io_annot.set("DBFreeDefvars");
		io_annot.end();
	return WRAP_DBFreeDefvars(a);
}

static void (*WRAP_DBFreeMultimesh) (DBmultimesh * a);
static void dissectio_DBFreeMultimesh (DBmultimesh * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBFreeMultimesh");
		io_annot.end();
	return WRAP_DBFreeMultimesh(a);
}

static void (*WRAP_DBFreeMultimeshadj) (DBmultimeshadj * a);
static void dissectio_DBFreeMultimeshadj (DBmultimeshadj * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBFreeMultimeshadj");
		io_annot.end();
	return WRAP_DBFreeMultimeshadj(a);
}

static void (*WRAP_DBFreeMultivar) (DBmultivar * a);
static void dissectio_DBFreeMultivar (DBmultivar * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBFreeMultivar");
		io_annot.end();
	return WRAP_DBFreeMultivar(a);
}

static void (*WRAP_DBFreeMultimat) (DBmultimat * a);
static void dissectio_DBFreeMultimat (DBmultimat * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBFreeMultimat");
		io_annot.end();
	return WRAP_DBFreeMultimat(a);
}

static void (*WRAP_DBFreeMultimatspecies) (DBmultimatspecies * a);
static void dissectio_DBFreeMultimatspecies (DBmultimatspecies * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBFreeMultimatspecies");
		io_annot.end();
	return WRAP_DBFreeMultimatspecies(a);
}

static void (*WRAP_DBFreeCompoundarray) (DBcompoundarray * a);
static void dissectio_DBFreeCompoundarray (DBcompoundarray * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBFreeCompoundarray");
		io_annot.end();
	return WRAP_DBFreeCompoundarray(a);
}

static void (*WRAP_DBFreeCurve) (DBcurve * a);
static void dissectio_DBFreeCurve (DBcurve * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBFreeCurve");
		io_annot.end();
	return WRAP_DBFreeCurve(a);
}

static void (*WRAP_DBFreeNamescheme) (DBnamescheme * a);
static void dissectio_DBFreeNamescheme (DBnamescheme * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBFreeNamescheme");
		io_annot.end();
	return WRAP_DBFreeNamescheme(a);
}

static void (*WRAP_DBFreeMrgvar) (DBmrgvar *mrgv);
static void dissectio_DBFreeMrgvar (DBmrgvar *mrgv){
		cali::Annotation io_annot("io");
		io_annot.set("DBFreeMrgvar");
		io_annot.end();
	return WRAP_DBFreeMrgvar(mrgv);
}

static void (*WRAP_DBFreeMrgtree) (DBmrgtree *tree);
static void dissectio_DBFreeMrgtree (DBmrgtree *tree){
		cali::Annotation io_annot("io");
		io_annot.set("DBFreeMrgtree");
		io_annot.end();
	return WRAP_DBFreeMrgtree(tree);
}

static void (*WRAP_DBFreeGroupelmap) (DBgroupelmap *map);
static void dissectio_DBFreeGroupelmap (DBgroupelmap *map){
		cali::Annotation io_annot("io");
		io_annot.set("DBFreeGroupelmap");
		io_annot.end();
	return WRAP_DBFreeGroupelmap(map);
}

static int (*WRAP_DBIsEmptyCurve) (DBcurve const *curve);
static int dissectio_DBIsEmptyCurve (DBcurve const *curve){
		cali::Annotation io_annot("io");
		io_annot.set("DBIsEmptyCurve");
		io_annot.end();
	return WRAP_DBIsEmptyCurve(curve);
}

static int (*WRAP_DBIsEmptyPointmesh) (DBpointmesh const *msh);
static int dissectio_DBIsEmptyPointmesh (DBpointmesh const *msh){
		cali::Annotation io_annot("io");
		io_annot.set("DBIsEmptyPointmesh");
		io_annot.end();
	return WRAP_DBIsEmptyPointmesh(msh);
}

static int (*WRAP_DBIsEmptyPointvar) (DBpointvar const *var);
static int dissectio_DBIsEmptyPointvar (DBpointvar const *var){
		cali::Annotation io_annot("io");
		io_annot.set("DBIsEmptyPointvar");
		io_annot.end();
	return WRAP_DBIsEmptyPointvar(var);
}

static int (*WRAP_DBIsEmptyMeshvar) (DBmeshvar const *var);
static int dissectio_DBIsEmptyMeshvar (DBmeshvar const *var){
		cali::Annotation io_annot("io");
		io_annot.set("DBIsEmptyMeshvar");
		io_annot.end();
	return WRAP_DBIsEmptyMeshvar(var);
}

static int (*WRAP_DBIsEmptyQuadmesh) (DBquadmesh const *msh);
static int dissectio_DBIsEmptyQuadmesh (DBquadmesh const *msh){
		cali::Annotation io_annot("io");
		io_annot.set("DBIsEmptyQuadmesh");
		io_annot.end();
	return WRAP_DBIsEmptyQuadmesh(msh);
}

static int (*WRAP_DBIsEmptyQuadvar) (DBquadvar const *var);
static int dissectio_DBIsEmptyQuadvar (DBquadvar const *var){
		cali::Annotation io_annot("io");
		io_annot.set("DBIsEmptyQuadvar");
		io_annot.end();
	return WRAP_DBIsEmptyQuadvar(var);
}

static int (*WRAP_DBIsEmptyUcdmesh) (DBucdmesh const *msh);
static int dissectio_DBIsEmptyUcdmesh (DBucdmesh const *msh){
		cali::Annotation io_annot("io");
		io_annot.set("DBIsEmptyUcdmesh");
		io_annot.end();
	return WRAP_DBIsEmptyUcdmesh(msh);
}

static int (*WRAP_DBIsEmptyFacelist) (DBfacelist const *fl);
static int dissectio_DBIsEmptyFacelist (DBfacelist const *fl){
		cali::Annotation io_annot("io");
		io_annot.set("DBIsEmptyFacelist");
		io_annot.end();
	return WRAP_DBIsEmptyFacelist(fl);
}

static int (*WRAP_DBIsEmptyZonelist) (DBzonelist const *zl);
static int dissectio_DBIsEmptyZonelist (DBzonelist const *zl){
		cali::Annotation io_annot("io");
		io_annot.set("DBIsEmptyZonelist");
		io_annot.end();
	return WRAP_DBIsEmptyZonelist(zl);
}

static int (*WRAP_DBIsEmptyPHZonelist) (DBphzonelist const *zl);
static int dissectio_DBIsEmptyPHZonelist (DBphzonelist const *zl){
		cali::Annotation io_annot("io");
		io_annot.set("DBIsEmptyPHZonelist");
		io_annot.end();
	return WRAP_DBIsEmptyPHZonelist(zl);
}

static int (*WRAP_DBIsEmptyUcdvar) (DBucdvar const *var);
static int dissectio_DBIsEmptyUcdvar (DBucdvar const *var){
		cali::Annotation io_annot("io");
		io_annot.set("DBIsEmptyUcdvar");
		io_annot.end();
	return WRAP_DBIsEmptyUcdvar(var);
}

static int (*WRAP_DBIsEmptyCsgmesh) (DBcsgmesh const *msh);
static int dissectio_DBIsEmptyCsgmesh (DBcsgmesh const *msh){
		cali::Annotation io_annot("io");
		io_annot.set("DBIsEmptyCsgmesh");
		io_annot.end();
	return WRAP_DBIsEmptyCsgmesh(msh);
}

static int (*WRAP_DBIsEmptyCSGZonelist) (DBcsgzonelist const *zl);
static int dissectio_DBIsEmptyCSGZonelist (DBcsgzonelist const *zl){
		cali::Annotation io_annot("io");
		io_annot.set("DBIsEmptyCSGZonelist");
		io_annot.end();
	return WRAP_DBIsEmptyCSGZonelist(zl);
}

static int (*WRAP_DBIsEmptyCsgvar) (DBcsgvar const *var);
static int dissectio_DBIsEmptyCsgvar (DBcsgvar const *var){
		cali::Annotation io_annot("io");
		io_annot.set("DBIsEmptyCsgvar");
		io_annot.end();
	return WRAP_DBIsEmptyCsgvar(var);
}

static int (*WRAP_DBIsEmptyMaterial) (DBmaterial const *mat);
static int dissectio_DBIsEmptyMaterial (DBmaterial const *mat){
		cali::Annotation io_annot("io");
		io_annot.set("DBIsEmptyMaterial");
		io_annot.end();
	return WRAP_DBIsEmptyMaterial(mat);
}

static int (*WRAP_DBIsEmptyMatspecies) (DBmatspecies const *spec);
static int dissectio_DBIsEmptyMatspecies (DBmatspecies const *spec){
		cali::Annotation io_annot("io");
		io_annot.set("DBIsEmptyMatspecies");
		io_annot.end();
	return WRAP_DBIsEmptyMatspecies(spec);
}

static int (*WRAP_DBGetObjtypeTag) (char const * a);
static int dissectio_DBGetObjtypeTag (char const * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetObjtypeTag");
		io_annot.end();
	return WRAP_DBGetObjtypeTag(a);
}

static DBobject * (*WRAP_DBMakeObject) (char const * a, int b, int c);
static DBobject * dissectio_DBMakeObject (char const * a, int b, int c){
		cali::Annotation io_annot("io");
		io_annot.set("DBMakeObject");
		io_annot.end();
	return WRAP_DBMakeObject(a, b, c);
}

static int (*WRAP_DBFreeObject) (DBobject * a);
static int dissectio_DBFreeObject (DBobject * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBFreeObject");
		io_annot.end();
	return WRAP_DBFreeObject(a);
}

static int (*WRAP_DBClearObject) (DBobject * a);
static int dissectio_DBClearObject (DBobject * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBClearObject");
		io_annot.end();
	return WRAP_DBClearObject(a);
}

static int (*WRAP_DBAddVarComponent) (DBobject * a, char const * b, char const * c);
static int dissectio_DBAddVarComponent (DBobject * a, char const * b, char const * c){
		cali::Annotation io_annot("io");
		io_annot.set("DBAddVarComponent");
		io_annot.end();
	return WRAP_DBAddVarComponent(a, b, c);
}

static int (*WRAP_DBAddIntComponent) (DBobject * a, char const * b, int c);
static int dissectio_DBAddIntComponent (DBobject * a, char const * b, int c){
		cali::Annotation io_annot("io");
		io_annot.set("DBAddIntComponent");
		io_annot.end();
	return WRAP_DBAddIntComponent(a, b, c);
}

static int (*WRAP_DBAddFltComponent) (DBobject * a, char const * b, double c);
static int dissectio_DBAddFltComponent (DBobject * a, char const * b, double c){
		cali::Annotation io_annot("io");
		io_annot.set("DBAddFltComponent");
		io_annot.end();
	return WRAP_DBAddFltComponent(a, b, c);
}

static int (*WRAP_DBAddDblComponent) (DBobject * a, char const * b, double c);
static int dissectio_DBAddDblComponent (DBobject * a, char const * b, double c){
		cali::Annotation io_annot("io");
		io_annot.set("DBAddDblComponent");
		io_annot.end();
	return WRAP_DBAddDblComponent(a, b, c);
}

static int (*WRAP_DBAddStrComponent) (DBobject * a, char const * b, char const * c);
static int dissectio_DBAddStrComponent (DBobject * a, char const * b, char const * c){
		cali::Annotation io_annot("io");
		io_annot.set("DBAddStrComponent");
		io_annot.end();
	return WRAP_DBAddStrComponent(a, b, c);
}

static int (*WRAP_DBGetComponentNames) (DBfile * a, char const * b, char *** c, char *** d);
static int dissectio_DBGetComponentNames (DBfile * a, char const * b, char *** c, char *** d){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetComponentNames");
		io_annot.end();
	return WRAP_DBGetComponentNames(a, b, c, d);
}

static DBobject * (*WRAP_DBGetObject) (DBfile * a, char const * b);
static DBobject * dissectio_DBGetObject (DBfile * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetObject");
		io_annot.end();
	return WRAP_DBGetObject(a, b);
}

static int (*WRAP_DBChangeObject) (DBfile * a, DBobject const * b);
static int dissectio_DBChangeObject (DBfile * a, DBobject const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBChangeObject");
		io_annot.end();
	return WRAP_DBChangeObject(a, b);
}

static int (*WRAP_DBWriteObject) (DBfile * a, DBobject const * b, int c);
static int dissectio_DBWriteObject (DBfile * a, DBobject const * b, int c){
		cali::Annotation io_annot("io");
		io_annot.set("DBWriteObject");
		io_annot.end();
	return WRAP_DBWriteObject(a, b, c);
}

static void * (*WRAP_DBGetComponent) (DBfile * a, char const * b, char const * c);
static void * dissectio_DBGetComponent (DBfile * a, char const * b, char const * c){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetComponent");
		io_annot.end();
	return WRAP_DBGetComponent(a, b, c);
}

static int (*WRAP_DBGetComponentType) (DBfile * a, char const * b, char const * c);
static int dissectio_DBGetComponentType (DBfile * a, char const * b, char const * c){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetComponentType");
		io_annot.end();
	return WRAP_DBGetComponentType(a, b, c);
}

static int (*WRAP_DBWriteComponent) (DBfile * a, DBobject * b, char const * c, char const * d, char const * e, void const * f, int g, long const * h);
static int dissectio_DBWriteComponent (DBfile * a, DBobject * b, char const * c, char const * d, char const * e, void const * f, int g, long const * h){
		cali::Annotation io_annot("io");
		io_annot.set("DBWriteComponent");
		io_annot.end();
	return WRAP_DBWriteComponent(a, b, c, d, e, f, g, h);
}

static int (*WRAP_DBWrite) (DBfile * a, char const * b, void const * c, int const * d, int e, int f);
static int dissectio_DBWrite (DBfile * a, char const * b, void const * c, int const * d, int e, int f){
		cali::Annotation io_annot("io");
		io_annot.set("DBWrite");
		io_annot.end();
	return WRAP_DBWrite(a, b, c, d, e, f);
}

static int (*WRAP_DBWriteSlice) (DBfile *dbfile, char const *array_name, void const * data, int datatype, int const *offsets, int const *lengths, int const *strides, int const *dims, int ndims);
static int dissectio_DBWriteSlice (DBfile *dbfile, char const *array_name, void const * data, int datatype, int const *offsets, int const *lengths, int const *strides, int const *dims, int ndims){
		cali::Annotation io_annot("io");
		io_annot.set("DBWriteSlice");
		io_annot.end();
	return WRAP_DBWriteSlice(dbfile, array_name, data, datatype, offsets, lengths, strides, dims, ndims);
}

static int (*WRAP_DBRead) (DBfile * a, char const * b, void * c);
static int dissectio_DBRead (DBfile * a, char const * b, void * c){
		cali::Annotation io_annot("io");
		io_annot.set("DBRead");
		io_annot.end();
	return WRAP_DBRead(a, b, c);
}

static int (*WRAP_DBReadVar) (DBfile * a, char const * b, void * c);
static int dissectio_DBReadVar (DBfile * a, char const * b, void * c){
		cali::Annotation io_annot("io");
		io_annot.set("DBReadVar");
		io_annot.end();
	return WRAP_DBReadVar(a, b, c);
}

static int (*WRAP_DBReadVarSlice) (DBfile * a, char const * b, int const * c, int const * d, int const * e, int f, void * g);
static int dissectio_DBReadVarSlice (DBfile * a, char const * b, int const * c, int const * d, int const * e, int f, void * g){
		cali::Annotation io_annot("io");
		io_annot.set("DBReadVarSlice");
		io_annot.end();
	return WRAP_DBReadVarSlice(a, b, c, d, e, f, g);
}

static DBcompoundarray * (*WRAP_DBGetCompoundarray) (DBfile * a, char const * b);
static DBcompoundarray * dissectio_DBGetCompoundarray (DBfile * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetCompoundarray");
		io_annot.end();
	return WRAP_DBGetCompoundarray(a, b);
}

static int (*WRAP_DBInqCompoundarray) (DBfile * a, char const * b, char *** c, int ** d, int * e, int * f, int * g);
static int dissectio_DBInqCompoundarray (DBfile * a, char const * b, char *** c, int ** d, int * e, int * f, int * g){
		cali::Annotation io_annot("io");
		io_annot.set("DBInqCompoundarray");
		io_annot.end();
	return WRAP_DBInqCompoundarray(a, b, c, d, e, f, g);
}

static void * (*WRAP_DBGetVar) (DBfile * a, char const * b);
static void * dissectio_DBGetVar (DBfile * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetVar");
		io_annot.end();
	return WRAP_DBGetVar(a, b);
}

static int (*WRAP_DBGetVarByteLength) (DBfile * a, char const * b);
static int dissectio_DBGetVarByteLength (DBfile * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetVarByteLength");
		io_annot.end();
	return WRAP_DBGetVarByteLength(a, b);
}

static int (*WRAP_DBGetVarLength) (DBfile * a, char const * b);
static int dissectio_DBGetVarLength (DBfile * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetVarLength");
		io_annot.end();
	return WRAP_DBGetVarLength(a, b);
}

static int (*WRAP_DBGetVarDims) (DBfile * a, char const * b, int c, int * d);
static int dissectio_DBGetVarDims (DBfile * a, char const * b, int c, int * d){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetVarDims");
		io_annot.end();
	return WRAP_DBGetVarDims(a, b, c, d);
}

static int (*WRAP_DBGetVarType) (DBfile * a, char const * b);
static int dissectio_DBGetVarType (DBfile * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetVarType");
		io_annot.end();
	return WRAP_DBGetVarType(a, b);
}

static DBObjectType (*WRAP_DBInqVarType) (DBfile * a, char const * b);
static DBObjectType dissectio_DBInqVarType (DBfile * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBInqVarType");
		io_annot.end();
	return WRAP_DBInqVarType(a, b);
}

static DBcurve * (*WRAP_DBGetCurve) (DBfile * a, char const * b);
static DBcurve * dissectio_DBGetCurve (DBfile * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetCurve");
		io_annot.end();
	return WRAP_DBGetCurve(a, b);
}

static DBdefvars * (*WRAP_DBGetDefvars) (DBfile * a, char const * b);
static DBdefvars * dissectio_DBGetDefvars (DBfile * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetDefvars");
		io_annot.end();
	return WRAP_DBGetDefvars(a, b);
}

static DBmaterial * (*WRAP_DBGetMaterial) (DBfile * a, char const * b);
static DBmaterial * dissectio_DBGetMaterial (DBfile * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetMaterial");
		io_annot.end();
	return WRAP_DBGetMaterial(a, b);
}

static DBmatspecies * (*WRAP_DBGetMatspecies) (DBfile * a, char const * b);
static DBmatspecies * dissectio_DBGetMatspecies (DBfile * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetMatspecies");
		io_annot.end();
	return WRAP_DBGetMatspecies(a, b);
}

static DBpointmesh * (*WRAP_DBGetPointmesh) (DBfile * a, char const * b);
static DBpointmesh * dissectio_DBGetPointmesh (DBfile * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetPointmesh");
		io_annot.end();
	return WRAP_DBGetPointmesh(a, b);
}

static DBmeshvar * (*WRAP_DBGetPointvar) (DBfile * a, char const * b);
static DBmeshvar * dissectio_DBGetPointvar (DBfile * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetPointvar");
		io_annot.end();
	return WRAP_DBGetPointvar(a, b);
}

static DBquadmesh * (*WRAP_DBGetQuadmesh) (DBfile * a, char const * b);
static DBquadmesh * dissectio_DBGetQuadmesh (DBfile * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetQuadmesh");
		io_annot.end();
	return WRAP_DBGetQuadmesh(a, b);
}

static DBquadvar * (*WRAP_DBGetQuadvar) (DBfile * a, char const * b);
static DBquadvar * dissectio_DBGetQuadvar (DBfile * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetQuadvar");
		io_annot.end();
	return WRAP_DBGetQuadvar(a, b);
}

static DBucdmesh * (*WRAP_DBGetUcdmesh) (DBfile * a, char const * b);
static DBucdmesh * dissectio_DBGetUcdmesh (DBfile * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetUcdmesh");
		io_annot.end();
	return WRAP_DBGetUcdmesh(a, b);
}

static DBucdvar * (*WRAP_DBGetUcdvar) (DBfile * a, char const * b);
static DBucdvar * dissectio_DBGetUcdvar (DBfile * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetUcdvar");
		io_annot.end();
	return WRAP_DBGetUcdvar(a, b);
}

static DBcsgmesh * (*WRAP_DBGetCsgmesh) (DBfile * a, char const * b);
static DBcsgmesh * dissectio_DBGetCsgmesh (DBfile * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetCsgmesh");
		io_annot.end();
	return WRAP_DBGetCsgmesh(a, b);
}

static DBcsgvar * (*WRAP_DBGetCsgvar) (DBfile * a, char const * b);
static DBcsgvar * dissectio_DBGetCsgvar (DBfile * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetCsgvar");
		io_annot.end();
	return WRAP_DBGetCsgvar(a, b);
}

static DBcsgzonelist * (*WRAP_DBGetCSGZonelist) (DBfile * a, char const * b);
static DBcsgzonelist * dissectio_DBGetCSGZonelist (DBfile * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetCSGZonelist");
		io_annot.end();
	return WRAP_DBGetCSGZonelist(a, b);
}

static DBfacelist * (*WRAP_DBGetFacelist) (DBfile * a, char const * b);
static DBfacelist * dissectio_DBGetFacelist (DBfile * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetFacelist");
		io_annot.end();
	return WRAP_DBGetFacelist(a, b);
}

static DBzonelist * (*WRAP_DBGetZonelist) (DBfile * a, char const * b);
static DBzonelist * dissectio_DBGetZonelist (DBfile * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetZonelist");
		io_annot.end();
	return WRAP_DBGetZonelist(a, b);
}

static DBphzonelist * (*WRAP_DBGetPHZonelist) (DBfile * a, char const * b);
static DBphzonelist * dissectio_DBGetPHZonelist (DBfile * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetPHZonelist");
		io_annot.end();
	return WRAP_DBGetPHZonelist(a, b);
}

static int (*WRAP_DBInqMeshname) (DBfile * a, char const * b, char * c);
static int dissectio_DBInqMeshname (DBfile * a, char const * b, char * c){
		cali::Annotation io_annot("io");
		io_annot.set("DBInqMeshname");
		io_annot.end();
	return WRAP_DBInqMeshname(a, b, c);
}

static int (*WRAP_DBInqMeshtype) (DBfile * a, char const * b);
static int dissectio_DBInqMeshtype (DBfile * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBInqMeshtype");
		io_annot.end();
	return WRAP_DBInqMeshtype(a, b);
}

static int (*WRAP_DBPutCompoundarray) (DBfile *dbfile, char const *name, char const * const *elemnames, int const *elemlens, int nelems, void const *values, int nvalues, int datatype, DBoptlist const * opts);
static int dissectio_DBPutCompoundarray (DBfile *dbfile, char const *name, char const * const *elemnames, int const *elemlens, int nelems, void const *values, int nvalues, int datatype, DBoptlist const * opts){
		cali::Annotation io_annot("io");
		io_annot.set("DBPutCompoundarray");
		io_annot.end();
	return WRAP_DBPutCompoundarray(dbfile, name, elemnames, elemlens, nelems, values, nvalues, datatype, opts);
}

static int (*WRAP_DBPutCurve) (DBfile *dbfile, char const * name, void const * xvals, void const * yvals, int datatype, int npts, DBoptlist const * opts);
static int dissectio_DBPutCurve (DBfile *dbfile, char const * name, void const * xvals, void const * yvals, int datatype, int npts, DBoptlist const * opts){
		cali::Annotation io_annot("io");
		io_annot.set("DBPutCurve");
		io_annot.end();
	return WRAP_DBPutCurve(dbfile, name, xvals, yvals, datatype, npts, opts);
}

static int (*WRAP_DBPutDefvars) (DBfile *dbfile, char const *name, int a, char const * const *names, int const *types, char const * const *defns, DBoptlist const * const *opts);
static int dissectio_DBPutDefvars (DBfile *dbfile, char const *name, int a, char const * const *names, int const *types, char const * const *defns, DBoptlist const * const *opts){
		cali::Annotation io_annot("io");
		io_annot.set("DBPutDefvars");
		io_annot.end();
	return WRAP_DBPutDefvars(dbfile, name, a, names, types, defns, opts);
}

static int (*WRAP_DBPutFacelist) (DBfile *dbfile, char const * a, int nfaces, int ndims, int const *nodelist, int lnodelist, int origin, int const *zoneno, int const *shapesize, int const *shapecnt, int nshapes, int const *types, int const *typelist, int ntypes);
static int dissectio_DBPutFacelist (DBfile *dbfile, char const * a, int nfaces, int ndims, int const *nodelist, int lnodelist, int origin, int const *zoneno, int const *shapesize, int const *shapecnt, int nshapes, int const *types, int const *typelist, int ntypes){
		cali::Annotation io_annot("io");
		io_annot.set("DBPutFacelist");
		io_annot.end();
	return WRAP_DBPutFacelist(dbfile, a, nfaces, ndims, nodelist, lnodelist, origin, zoneno, shapesize, shapecnt, nshapes, types, typelist, ntypes);
}

static int (*WRAP_DBPutMaterial) (DBfile *dbfile, char const *name, char const *meshname, int nmat, int const *matnos, int const *matlist, int const *dims, int ndims, int const *mix_next, int const *mix_mat, int const *mix_zone, DBVCP1_t mix_vf, int mixlen, int datatype, DBoptlist const *opts);
static int dissectio_DBPutMaterial (DBfile *dbfile, char const *name, char const *meshname, int nmat, int const *matnos, int const *matlist, int const *dims, int ndims, int const *mix_next, int const *mix_mat, int const *mix_zone, DBVCP1_t mix_vf, int mixlen, int datatype, DBoptlist const *opts){
		cali::Annotation io_annot("io");
		io_annot.set("DBPutMaterial");
		io_annot.end();
	return WRAP_DBPutMaterial(dbfile, name, meshname, nmat, matnos, matlist, dims, ndims, mix_next, mix_mat, mix_zone, mix_vf, mixlen, datatype, opts);
}

static int (*WRAP_DBPutMatspecies) (struct DBfile *dbfile, char const *name, char const *matnam, int nmat, int const *nmatspec, int const *speclist, int const *dims, int ndims, int nspecies_mf, DBVCP1_t species_mf, int const *mix_speclist, int mixlen, int datatype, DBoptlist const *optlist);
static int dissectio_DBPutMatspecies (struct DBfile *dbfile, char const *name, char const *matnam, int nmat, int const *nmatspec, int const *speclist, int const *dims, int ndims, int nspecies_mf, DBVCP1_t species_mf, int const *mix_speclist, int mixlen, int datatype, DBoptlist const *optlist){
		cali::Annotation io_annot("io");
		io_annot.set("DBPutMatspecies");
		io_annot.end();
	return WRAP_DBPutMatspecies(dbfile, name, matnam, nmat, nmatspec, speclist, dims, ndims, nspecies_mf, species_mf, mix_speclist, mixlen, datatype, optlist);
}

static int (*WRAP_DBPutPointmesh) (DBfile * a, char const * b, int c, DBVCP2_t d, int e, int f, DBoptlist const * g);
static int dissectio_DBPutPointmesh (DBfile * a, char const * b, int c, DBVCP2_t d, int e, int f, DBoptlist const * g){
		cali::Annotation io_annot("io");
		io_annot.set("DBPutPointmesh");
		io_annot.end();
	return WRAP_DBPutPointmesh(a, b, c, d, e, f, g);
}

static int (*WRAP_DBPutPointvar) (DBfile * a, char const * b, char const * c, int d, DBVCP2_t e, int f, int g, DBoptlist const * h);
static int dissectio_DBPutPointvar (DBfile * a, char const * b, char const * c, int d, DBVCP2_t e, int f, int g, DBoptlist const * h){
		cali::Annotation io_annot("io");
		io_annot.set("DBPutPointvar");
		io_annot.end();
	return WRAP_DBPutPointvar(a, b, c, d, e, f, g, h);
}

static int (*WRAP_DBPutPointvar1) (DBfile * a, char const * b, char const * c, DBVCP1_t d, int e, int f, DBoptlist const * g);
static int dissectio_DBPutPointvar1 (DBfile * a, char const * b, char const * c, DBVCP1_t d, int e, int f, DBoptlist const * g){
		cali::Annotation io_annot("io");
		io_annot.set("DBPutPointvar1");
		io_annot.end();
	return WRAP_DBPutPointvar1(a, b, c, d, e, f, g);
}

static int (*WRAP_DBPutQuadmesh) (DBfile * a, char const * b, char const * const * c, DBVCP2_t d, int const * e, int f, int g, int h, DBoptlist const * i);
static int dissectio_DBPutQuadmesh (DBfile * a, char const * b, char const * const * c, DBVCP2_t d, int const * e, int f, int g, int h, DBoptlist const * i){
		cali::Annotation io_annot("io");
		io_annot.set("DBPutQuadmesh");
		io_annot.end();
	return WRAP_DBPutQuadmesh(a, b, c, d, e, f, g, h, i);
}

static int (*WRAP_DBPutQuadvar) (DBfile * a, char const * b, char const * c, int d, char const * const * e, DBVCP2_t f, int const * g, int h, DBVCP2_t i, int j, int k, int l, DBoptlist const * m);
static int dissectio_DBPutQuadvar (DBfile * a, char const * b, char const * c, int d, char const * const * e, DBVCP2_t f, int const * g, int h, DBVCP2_t i, int j, int k, int l, DBoptlist const * m){
		cali::Annotation io_annot("io");
		io_annot.set("DBPutQuadvar");
		io_annot.end();
	return WRAP_DBPutQuadvar(a, b, c, d, e, f, g, h, i, j, k, l, m);
}

static int (*WRAP_DBPutQuadvar1) (DBfile * a, char const * b, char const * c, DBVCP1_t d, int const * e, int f, DBVCP1_t g, int h, int i, int j, DBoptlist const * k);
static int dissectio_DBPutQuadvar1 (DBfile * a, char const * b, char const * c, DBVCP1_t d, int const * e, int f, DBVCP1_t g, int h, int i, int j, DBoptlist const * k){
		cali::Annotation io_annot("io");
		io_annot.set("DBPutQuadvar1");
		io_annot.end();
	return WRAP_DBPutQuadvar1(a, b, c, d, e, f, g, h, i, j, k);
}

static int (*WRAP_DBPutUcdmesh) (DBfile * a, char const * b, int c, char const * const * d, DBVCP2_t e, int f, int g, char const * h, char const * i, int j, DBoptlist const * k);
static int dissectio_DBPutUcdmesh (DBfile * a, char const * b, int c, char const * const * d, DBVCP2_t e, int f, int g, char const * h, char const * i, int j, DBoptlist const * k){
		cali::Annotation io_annot("io");
		io_annot.set("DBPutUcdmesh");
		io_annot.end();
	return WRAP_DBPutUcdmesh(a, b, c, d, e, f, g, h, i, j, k);
}

static int (*WRAP_DBPutUcdsubmesh) (DBfile * a, char const * b, char const * c, int d, char const * e, char const * f, DBoptlist const * g);
static int dissectio_DBPutUcdsubmesh (DBfile * a, char const * b, char const * c, int d, char const * e, char const * f, DBoptlist const * g){
		cali::Annotation io_annot("io");
		io_annot.set("DBPutUcdsubmesh");
		io_annot.end();
	return WRAP_DBPutUcdsubmesh(a, b, c, d, e, f, g);
}

static int (*WRAP_DBPutUcdvar) (DBfile * a, char const * b, char const * c, int d, char const * const * e, DBVCP2_t f, int g, DBVCP2_t h, int i, int j, int k, DBoptlist const * l);
static int dissectio_DBPutUcdvar (DBfile * a, char const * b, char const * c, int d, char const * const * e, DBVCP2_t f, int g, DBVCP2_t h, int i, int j, int k, DBoptlist const * l){
		cali::Annotation io_annot("io");
		io_annot.set("DBPutUcdvar");
		io_annot.end();
	return WRAP_DBPutUcdvar(a, b, c, d, e, f, g, h, i, j, k, l);
}

static int (*WRAP_DBPutUcdvar1) (DBfile * a, char const * b, char const * c, DBVCP1_t d, int e, DBVCP1_t f, int g, int h, int i, DBoptlist const * j);
static int dissectio_DBPutUcdvar1 (DBfile * a, char const * b, char const * c, DBVCP1_t d, int e, DBVCP1_t f, int g, int h, int i, DBoptlist const * j){
		cali::Annotation io_annot("io");
		io_annot.set("DBPutUcdvar1");
		io_annot.end();
	return WRAP_DBPutUcdvar1(a, b, c, d, e, f, g, h, i, j);
}

static int (*WRAP_DBPutZonelist) (DBfile * a, char const * b, int c, int d, int const * e, int f, int g, int const * h, int const * i, int j);
static int dissectio_DBPutZonelist (DBfile * a, char const * b, int c, int d, int const * e, int f, int g, int const * h, int const * i, int j){
		cali::Annotation io_annot("io");
		io_annot.set("DBPutZonelist");
		io_annot.end();
	return WRAP_DBPutZonelist(a, b, c, d, e, f, g, h, i, j);
}

static int (*WRAP_DBPutZonelist2) (DBfile * a, char const * b, int c, int d, int const * e, int f, int g, int h, int i, int const * j, int const * k, int const * l, int m, DBoptlist const * n);
static int dissectio_DBPutZonelist2 (DBfile * a, char const * b, int c, int d, int const * e, int f, int g, int h, int i, int const * j, int const * k, int const * l, int m, DBoptlist const * n){
		cali::Annotation io_annot("io");
		io_annot.set("DBPutZonelist2");
		io_annot.end();
	return WRAP_DBPutZonelist2(a, b, c, d, e, f, g, h, i, j, k, l, m, n);
}

static int (*WRAP_DBPutPHZonelist) (DBfile * a, char const * b, int c, int const * d, int e, int const * f, char const * g, int h, int const * i, int j, int const * k, int l, int m, int n, DBoptlist const * o);
static int dissectio_DBPutPHZonelist (DBfile * a, char const * b, int c, int const * d, int e, int const * f, char const * g, int h, int const * i, int j, int const * k, int l, int m, int n, DBoptlist const * o){
		cali::Annotation io_annot("io");
		io_annot.set("DBPutPHZonelist");
		io_annot.end();
	return WRAP_DBPutPHZonelist(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o);
}

static int (*WRAP_DBPutCsgmesh) (DBfile * a, char const * b, int c, int d, int const * e, int const * f, void const * g, int h, int i, double const * j, char const * k, DBoptlist const * l);
static int dissectio_DBPutCsgmesh (DBfile * a, char const * b, int c, int d, int const * e, int const * f, void const * g, int h, int i, double const * j, char const * k, DBoptlist const * l){
		cali::Annotation io_annot("io");
		io_annot.set("DBPutCsgmesh");
		io_annot.end();
	return WRAP_DBPutCsgmesh(a, b, c, d, e, f, g, h, i, j, k, l);
}

static int (*WRAP_DBPutCSGZonelist) (DBfile * a, char const * b, int c, int const * d, int const * e, int const * g, void const * h, int i, int j, int k, int const * l, DBoptlist const * m);
static int dissectio_DBPutCSGZonelist (DBfile * a, char const * b, int c, int const * d, int const * e, int const * g, void const * h, int i, int j, int k, int const * l, DBoptlist const * m){
		cali::Annotation io_annot("io");
		io_annot.set("DBPutCSGZonelist");
		io_annot.end();
	return WRAP_DBPutCSGZonelist(a, b, c, d, e, g, h, i, j, k, l, m);
}

static int (*WRAP_DBPutCsgvar) (DBfile * a, char const * b, char const * c, int d, char const * const * e, DBVCP2_t f, int g, int h, int i, DBoptlist const * j);
static int dissectio_DBPutCsgvar (DBfile * a, char const * b, char const * c, int d, char const * const * e, DBVCP2_t f, int g, int h, int i, DBoptlist const * j){
		cali::Annotation io_annot("io");
		io_annot.set("DBPutCsgvar");
		io_annot.end();
	return WRAP_DBPutCsgvar(a, b, c, d, e, f, g, h, i, j);
}

static void (*WRAP_DBPrintMrgtree) (DBmrgtnode *tnode, int walk_order, void *data);
static void dissectio_DBPrintMrgtree (DBmrgtnode *tnode, int walk_order, void *data){
		cali::Annotation io_annot("io");
		io_annot.set("DBPrintMrgtree");
		io_annot.end();
	return WRAP_DBPrintMrgtree(tnode, walk_order, data);
}

static void (*WRAP_DBLinearizeMrgtree) (DBmrgtnode *tnode, int walk_order, void *data);
static void dissectio_DBLinearizeMrgtree (DBmrgtnode *tnode, int walk_order, void *data){
		cali::Annotation io_annot("io");
		io_annot.set("DBLinearizeMrgtree");
		io_annot.end();
	return WRAP_DBLinearizeMrgtree(tnode, walk_order, data);
}

static void (*WRAP_DBWalkMrgtree) (DBmrgtree const *tree, DBmrgwalkcb cb, void *wdata, int traversal_order);
static void dissectio_DBWalkMrgtree (DBmrgtree const *tree, DBmrgwalkcb cb, void *wdata, int traversal_order){
		cali::Annotation io_annot("io");
		io_annot.set("DBWalkMrgtree");
		io_annot.end();
	return WRAP_DBWalkMrgtree(tree, cb, wdata, traversal_order);
}

static DBmrgtree * (*WRAP_DBMakeMrgtree) (int source_mesh_type, int mrgtree_info, int max_root_descendents, DBoptlist *opts);
static DBmrgtree * dissectio_DBMakeMrgtree (int source_mesh_type, int mrgtree_info, int max_root_descendents, DBoptlist *opts){
		cali::Annotation io_annot("io");
		io_annot.set("DBMakeMrgtree");
		io_annot.end();
	return WRAP_DBMakeMrgtree(source_mesh_type, mrgtree_info, max_root_descendents, opts);
}

static int (*WRAP_DBAddRegion) (DBmrgtree *tree, char const *region_name, int type_info_bits, int max_descendents, char const *maps_name, int nsegs, int const *seg_ids, int const *seg_sizes, int const *seg_types, DBoptlist const *opts);
static int dissectio_DBAddRegion (DBmrgtree *tree, char const *region_name, int type_info_bits, int max_descendents, char const *maps_name, int nsegs, int const *seg_ids, int const *seg_sizes, int const *seg_types, DBoptlist const *opts){
		cali::Annotation io_annot("io");
		io_annot.set("DBAddRegion");
		io_annot.end();
	return WRAP_DBAddRegion(tree, region_name, type_info_bits, max_descendents, maps_name, nsegs, seg_ids, seg_sizes, seg_types, opts);
}

static int (*WRAP_DBAddRegionArray) (DBmrgtree *tree, int nregn, char const * const *regn_names, int type_info_bits, char const *maps_name, int nsegs, int const *seg_ids, int const *seg_sizes, int const *seg_types, DBoptlist const *opts);
static int dissectio_DBAddRegionArray (DBmrgtree *tree, int nregn, char const * const *regn_names, int type_info_bits, char const *maps_name, int nsegs, int const *seg_ids, int const *seg_sizes, int const *seg_types, DBoptlist const *opts){
		cali::Annotation io_annot("io");
		io_annot.set("DBAddRegionArray");
		io_annot.end();
	return WRAP_DBAddRegionArray(tree, nregn, regn_names, type_info_bits, maps_name, nsegs, seg_ids, seg_sizes, seg_types, opts);
}

static int (*WRAP_DBSetCwr) (DBmrgtree *tree, char const *path);
static int dissectio_DBSetCwr (DBmrgtree *tree, char const *path){
		cali::Annotation io_annot("io");
		io_annot.set("DBSetCwr");
		io_annot.end();
	return WRAP_DBSetCwr(tree, path);
}

static char const * (*WRAP_DBGetCwr) (DBmrgtree *tree);
static char const * dissectio_DBGetCwr (DBmrgtree *tree){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetCwr");
		io_annot.end();
	return WRAP_DBGetCwr(tree);
}

static int (*WRAP_DBPutMrgtree) (DBfile *dbfile, char const *mrg_tree_name, char const *mesh_name, DBmrgtree const *tree, DBoptlist const *opts);
static int dissectio_DBPutMrgtree (DBfile *dbfile, char const *mrg_tree_name, char const *mesh_name, DBmrgtree const *tree, DBoptlist const *opts){
		cali::Annotation io_annot("io");
		io_annot.set("DBPutMrgtree");
		io_annot.end();
	return WRAP_DBPutMrgtree(dbfile, mrg_tree_name, mesh_name, tree, opts);
}

static int (*WRAP_DBPutMrgvar) (DBfile *dbfile, char const *name, char const *mrgt_name, int ncomps, char const * const *compnames, int nregns, char const * const *reg_pnames, int datatype, DBVCP2_t data, DBoptlist const *opts);
static int dissectio_DBPutMrgvar (DBfile *dbfile, char const *name, char const *mrgt_name, int ncomps, char const * const *compnames, int nregns, char const * const *reg_pnames, int datatype, DBVCP2_t data, DBoptlist const *opts){
		cali::Annotation io_annot("io");
		io_annot.set("DBPutMrgvar");
		io_annot.end();
	return WRAP_DBPutMrgvar(dbfile, name, mrgt_name, ncomps, compnames, nregns, reg_pnames, datatype, data, opts);
}

static int (*WRAP_DBPutGroupelmap) (DBfile *dbfile, char const *map_name, int num_segments, int const *groupel_types, int const *segment_lengths, int const *segment_ids, int const * const *segment_data, DBVCP2_t segment_fracs, int fracs_data_type, DBoptlist const *opts);
static int dissectio_DBPutGroupelmap (DBfile *dbfile, char const *map_name, int num_segments, int const *groupel_types, int const *segment_lengths, int const *segment_ids, int const * const *segment_data, DBVCP2_t segment_fracs, int fracs_data_type, DBoptlist const *opts){
		cali::Annotation io_annot("io");
		io_annot.set("DBPutGroupelmap");
		io_annot.end();
	return WRAP_DBPutGroupelmap(dbfile, map_name, num_segments, groupel_types, segment_lengths, segment_ids, segment_data, segment_fracs, fracs_data_type, opts);
}

static DBmrgvar * (*WRAP_DBGetMrgvar) (DBfile *dbfile, char const *name);
static DBmrgvar * dissectio_DBGetMrgvar (DBfile *dbfile, char const *name){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetMrgvar");
		io_annot.end();
	return WRAP_DBGetMrgvar(dbfile, name);
}

static char const * (*WRAP_DBGetName) (DBnamescheme const *ns, int natnum);
static char const * dissectio_DBGetName (DBnamescheme const *ns, int natnum){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetName");
		io_annot.end();
	return WRAP_DBGetName(ns, natnum);
}

static DBmultimesh * (*WRAP_DBGetMultimesh) (DBfile * a, char const * b);
static DBmultimesh * dissectio_DBGetMultimesh (DBfile * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetMultimesh");
		io_annot.end();
	return WRAP_DBGetMultimesh(a, b);
}

static DBmultimeshadj * (*WRAP_DBGetMultimeshadj) (DBfile * a, char const * b, int c, int const * d);
static DBmultimeshadj * dissectio_DBGetMultimeshadj (DBfile * a, char const * b, int c, int const * d){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetMultimeshadj");
		io_annot.end();
	return WRAP_DBGetMultimeshadj(a, b, c, d);
}

static DBmultivar * (*WRAP_DBGetMultivar) (DBfile * a, char const * b);
static DBmultivar * dissectio_DBGetMultivar (DBfile * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetMultivar");
		io_annot.end();
	return WRAP_DBGetMultivar(a, b);
}

static DBmultimat * (*WRAP_DBGetMultimat) (DBfile * a, char const * b);
static DBmultimat * dissectio_DBGetMultimat (DBfile * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetMultimat");
		io_annot.end();
	return WRAP_DBGetMultimat(a, b);
}

static DBmultimatspecies * (*WRAP_DBGetMultimatspecies) (DBfile * a, char const * b);
static DBmultimatspecies * dissectio_DBGetMultimatspecies (DBfile * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetMultimatspecies");
		io_annot.end();
	return WRAP_DBGetMultimatspecies(a, b);
}

static int (*WRAP_DBPutMultimesh) (DBfile * a, char const * b, int c, char const * const * d, int const * e, DBoptlist const * f);
static int dissectio_DBPutMultimesh (DBfile * a, char const * b, int c, char const * const * d, int const * e, DBoptlist const * f){
		cali::Annotation io_annot("io");
		io_annot.set("DBPutMultimesh");
		io_annot.end();
	return WRAP_DBPutMultimesh(a, b, c, d, e, f);
}

static int (*WRAP_DBPutMultimeshadj) (DBfile * a, char const * b, int c, int const * d, int const * e, int const * f, int const * g, int const * h, int const * const * i, int const * j, int const * const * k, DBoptlist const *optlist);
static int dissectio_DBPutMultimeshadj (DBfile * a, char const * b, int c, int const * d, int const * e, int const * f, int const * g, int const * h, int const * const * i, int const * j, int const * const * k, DBoptlist const *optlist){
		cali::Annotation io_annot("io");
		io_annot.set("DBPutMultimeshadj");
		io_annot.end();
	return WRAP_DBPutMultimeshadj(a, b, c, d, e, f, g, h, i, j, k, optlist);
}

static int (*WRAP_DBPutMultivar) (DBfile * a, char const * b, int c, char const * const * d, int const * e, DBoptlist const * opts);
static int dissectio_DBPutMultivar (DBfile * a, char const * b, int c, char const * const * d, int const * e, DBoptlist const * opts){
		cali::Annotation io_annot("io");
		io_annot.set("DBPutMultivar");
		io_annot.end();
	return WRAP_DBPutMultivar(a, b, c, d, e, opts);
}

static int (*WRAP_DBPutMultimat) (DBfile * a, char const * b, int c, char const * const * d, DBoptlist const * e);
static int dissectio_DBPutMultimat (DBfile * a, char const * b, int c, char const * const * d, DBoptlist const * e){
		cali::Annotation io_annot("io");
		io_annot.set("DBPutMultimat");
		io_annot.end();
	return WRAP_DBPutMultimat(a, b, c, d, e);
}

static int (*WRAP_DBPutMultimatspecies) (DBfile * a, char const * b, int c, char const * const * d, DBoptlist const * e);
static int dissectio_DBPutMultimatspecies (DBfile * a, char const * b, int c, char const * const * d, DBoptlist const * e){
		cali::Annotation io_annot("io");
		io_annot.set("DBPutMultimatspecies");
		io_annot.end();
	return WRAP_DBPutMultimatspecies(a, b, c, d, e);
}

static DBoptlist * (*WRAP_DBMakeOptlist) (int a);
static DBoptlist * dissectio_DBMakeOptlist (int a){
		cali::Annotation io_annot("io");
		io_annot.set("DBMakeOptlist");
		io_annot.end();
	return WRAP_DBMakeOptlist(a);
}

static int (*WRAP_DBClearOptlist) (DBoptlist * a);
static int dissectio_DBClearOptlist (DBoptlist * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBClearOptlist");
		io_annot.end();
	return WRAP_DBClearOptlist(a);
}

static int (*WRAP_DBFreeOptlist) (DBoptlist * a);
static int dissectio_DBFreeOptlist (DBoptlist * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBFreeOptlist");
		io_annot.end();
	return WRAP_DBFreeOptlist(a);
}

static int (*WRAP_DBAddOption) (DBoptlist * a, int b, void * c);
static int dissectio_DBAddOption (DBoptlist * a, int b, void * c){
		cali::Annotation io_annot("io");
		io_annot.set("DBAddOption");
		io_annot.end();
	return WRAP_DBAddOption(a, b, c);
}

static void * (*WRAP_DBGetOption) (DBoptlist const * a, int b);
static void * dissectio_DBGetOption (DBoptlist const * a, int b){
		cali::Annotation io_annot("io");
		io_annot.set("DBGetOption");
		io_annot.end();
	return WRAP_DBGetOption(a, b);
}

static int (*WRAP_DBClearOption) (DBoptlist * a, int b);
static int dissectio_DBClearOption (DBoptlist * a, int b){
		cali::Annotation io_annot("io");
		io_annot.set("DBClearOption");
		io_annot.end();
	return WRAP_DBClearOption(a, b);
}

static int (*WRAP_DBAnnotateUcdmesh) (DBucdmesh * a);
static int dissectio_DBAnnotateUcdmesh (DBucdmesh * a){
		cali::Annotation io_annot("io");
		io_annot.set("DBAnnotateUcdmesh");
		io_annot.end();
	return WRAP_DBAnnotateUcdmesh(a);
}

static DBfacelist * (*WRAP_DBCalcExternalFacelist) (int * a, int b, int c, int * d, int * e, int f, int * g, int h);
static DBfacelist * dissectio_DBCalcExternalFacelist (int * a, int b, int c, int * d, int * e, int f, int * g, int h){
		cali::Annotation io_annot("io");
		io_annot.set("DBCalcExternalFacelist");
		io_annot.end();
	return WRAP_DBCalcExternalFacelist(a, b, c, d, e, f, g, h);
}

static DBfacelist * (*WRAP_DBCalcExternalFacelist2) (int * a, int b, int c, int d, int e, int * f, int * g, int * h, int i, int * j, int k);
static DBfacelist * dissectio_DBCalcExternalFacelist2 (int * a, int b, int c, int d, int e, int * f, int * g, int * h, int i, int * j, int k){
		cali::Annotation io_annot("io");
		io_annot.set("DBCalcExternalFacelist2");
		io_annot.end();
	return WRAP_DBCalcExternalFacelist2(a, b, c, d, e, f, g, h, i, j, k);
}

static char * (*WRAP_DBJoinPath) (char const * a, char const * b);
static char * dissectio_DBJoinPath (char const * a, char const * b){
		cali::Annotation io_annot("io");
		io_annot.set("DBJoinPath");
		io_annot.end();
	return WRAP_DBJoinPath(a, b);
}

static void (*WRAP_DBStringArrayToStringList) (char const * const *strArray, int n, char **strList, int *m);
static void dissectio_DBStringArrayToStringList (char const * const *strArray, int n, char **strList, int *m){
		cali::Annotation io_annot("io");
		io_annot.set("DBStringArrayToStringList");
		io_annot.end();
	return WRAP_DBStringArrayToStringList(strArray, n, strList, m);
}

static char ** (*WRAP_DBStringListToStringArray) (char const *strList, int *n, int skipSemicolonAtIndexZero);
static char ** dissectio_DBStringListToStringArray (char const *strList, int *n, int skipSemicolonAtIndexZero){
		cali::Annotation io_annot("io");
		io_annot.set("DBStringListToStringArray");
		io_annot.end();
	return WRAP_DBStringListToStringArray(strList, n, skipSemicolonAtIndexZero);
}

static int (*WRAP_DBIsDifferentDouble) (double a, double b, double abstol, double reltol, double reltol_eps);
static int dissectio_DBIsDifferentDouble (double a, double b, double abstol, double reltol, double reltol_eps){
		cali::Annotation io_annot("io");
		io_annot.set("DBIsDifferentDouble");
		io_annot.end();
	return WRAP_DBIsDifferentDouble(a, b, abstol, reltol, reltol_eps);
}

static int (*WRAP_DBIsDifferentLongLong) (long long a, long long b, double abstol, double reltol, double reltol_eps);
static int dissectio_DBIsDifferentLongLong (long long a, long long b, double abstol, double reltol, double reltol_eps){
		cali::Annotation io_annot("io");
		io_annot.set("DBIsDifferentLongLong");
		io_annot.end();
	return WRAP_DBIsDifferentLongLong(a, b, abstol, reltol, reltol_eps);
}

static void * (*WRAP_DBFortranAccessPointer) (int value);
static void * dissectio_DBFortranAccessPointer (int value){
		cali::Annotation io_annot("io");
		io_annot.set("DBFortranAccessPointer");
		io_annot.end();
	return WRAP_DBFortranAccessPointer(value);
}

static int (*WRAP_DBFortranAllocPointer) (void *pointer);
static int dissectio_DBFortranAllocPointer (void *pointer){
		cali::Annotation io_annot("io");
		io_annot.set("DBFortranAllocPointer");
		io_annot.end();
	return WRAP_DBFortranAllocPointer(pointer);
}

static void (*WRAP_DBFortranRemovePointer) (int value);
static void dissectio_DBFortranRemovePointer (int value){
		cali::Annotation io_annot("io");
		io_annot.set("DBFortranRemovePointer");
		io_annot.end();
	return WRAP_DBFortranRemovePointer(value);
}

static char * (*WRAP__db_safe_strdup) (const char * a);
static char * dissectio__db_safe_strdup (const char * a){
		cali::Annotation io_annot("io");
		io_annot.set("_db_safe_strdup");
		io_annot.end();
	return WRAP__db_safe_strdup(a);
}


struct gotcha_binding_t wrap_all_silo [] = {
	{ "DBShowErrors", dissectio_DBShowErrors, &WRAP_DBShowErrors },
	{ "DBErrString", dissectio_DBErrString, &WRAP_DBErrString },
	{ "DBErrFuncname", dissectio_DBErrFuncname, &WRAP_DBErrFuncname },
	{ "DBErrfunc", dissectio_DBErrfunc, &WRAP_DBErrfunc },
	{ "DBErrno", dissectio_DBErrno, &WRAP_DBErrno },
	{ "DBErrlvl", dissectio_DBErrlvl, &WRAP_DBErrlvl },
	{ "DBSetDataReadMask2", dissectio_DBSetDataReadMask2, &WRAP_DBSetDataReadMask2 },
	{ "DBGetDataReadMask2", dissectio_DBGetDataReadMask2, &WRAP_DBGetDataReadMask2 },
	{ "DBGetDatatypeString", dissectio_DBGetDatatypeString, &WRAP_DBGetDatatypeString },
	{ "DBSetAllowOverwrites", dissectio_DBSetAllowOverwrites, &WRAP_DBSetAllowOverwrites },
	{ "DBGetAllowOverwrites", dissectio_DBGetAllowOverwrites, &WRAP_DBGetAllowOverwrites },
	{ "DBSetAllowEmptyObjects", dissectio_DBSetAllowEmptyObjects, &WRAP_DBSetAllowEmptyObjects },
	{ "DBGetAllowEmptyObjects", dissectio_DBGetAllowEmptyObjects, &WRAP_DBGetAllowEmptyObjects },
	{ "DBSetEnableChecksums", dissectio_DBSetEnableChecksums, &WRAP_DBSetEnableChecksums },
	{ "DBGetEnableChecksums", dissectio_DBGetEnableChecksums, &WRAP_DBGetEnableChecksums },
	{ "DBSetCompression", dissectio_DBSetCompression, &WRAP_DBSetCompression },
	{ "DBGetCompression", dissectio_DBGetCompression, &WRAP_DBGetCompression },
	{ "DBSetFriendlyHDF5Names", dissectio_DBSetFriendlyHDF5Names, &WRAP_DBSetFriendlyHDF5Names },
	{ "DBGetFriendlyHDF5Names", dissectio_DBGetFriendlyHDF5Names, &WRAP_DBGetFriendlyHDF5Names },
	{ "DBSetDeprecateWarnings", dissectio_DBSetDeprecateWarnings, &WRAP_DBSetDeprecateWarnings },
	{ "DBGetDeprecateWarnings", dissectio_DBGetDeprecateWarnings, &WRAP_DBGetDeprecateWarnings },
	{ "DBSetUnknownDriverPriorities", dissectio_DBSetUnknownDriverPriorities, &WRAP_DBSetUnknownDriverPriorities },
	{ "DBGetUnknownDriverPriorities", dissectio_DBGetUnknownDriverPriorities, &WRAP_DBGetUnknownDriverPriorities },
	{ "DBRegisterFileOptionsSet", dissectio_DBRegisterFileOptionsSet, &WRAP_DBRegisterFileOptionsSet },
	{ "DBUnregisterFileOptionsSet", dissectio_DBUnregisterFileOptionsSet, &WRAP_DBUnregisterFileOptionsSet },
	{ "DBUnregisterAllFileOptionsSets", dissectio_DBUnregisterAllFileOptionsSets, &WRAP_DBUnregisterAllFileOptionsSets },
	{ "DBVersion", dissectio_DBVersion, &WRAP_DBVersion },
	{ "DBVersionDigits", dissectio_DBVersionDigits, &WRAP_DBVersionDigits },
	{ "DBVersionGE", dissectio_DBVersionGE, &WRAP_DBVersionGE },
	{ "DBVariableNameValid", dissectio_DBVariableNameValid, &WRAP_DBVariableNameValid },
	{ "DBForceSingle", dissectio_DBForceSingle, &WRAP_DBForceSingle },
	{ "DBOpenReal", dissectio_DBOpenReal, &WRAP_DBOpenReal },
	{ "DBCreateReal", dissectio_DBCreateReal, &WRAP_DBCreateReal },
	{ "DBInqFileReal", dissectio_DBInqFileReal, &WRAP_DBInqFileReal },
	{ "DBClose", dissectio_DBClose, &WRAP_DBClose },
	{ "DBGetToc", dissectio_DBGetToc, &WRAP_DBGetToc },
	{ "DBNewToc", dissectio_DBNewToc, &WRAP_DBNewToc },
	{ "DBGrabDriver", dissectio_DBGrabDriver, &WRAP_DBGrabDriver },
	{ "DBUngrabDriver", dissectio_DBUngrabDriver, &WRAP_DBUngrabDriver },
	{ "DBGetDriverType", dissectio_DBGetDriverType, &WRAP_DBGetDriverType },
	{ "DBGetDriverTypeFromPath", dissectio_DBGetDriverTypeFromPath, &WRAP_DBGetDriverTypeFromPath },
	{ "DBVersionGEFileVersion", dissectio_DBVersionGEFileVersion, &WRAP_DBVersionGEFileVersion },
	{ "DBFileVersion", dissectio_DBFileVersion, &WRAP_DBFileVersion },
	{ "DBFileVersionDigits", dissectio_DBFileVersionDigits, &WRAP_DBFileVersionDigits },
	{ "DBFileVersionGE", dissectio_DBFileVersionGE, &WRAP_DBFileVersionGE },
	{ "DBGetDir", dissectio_DBGetDir, &WRAP_DBGetDir },
	{ "DBSetDir", dissectio_DBSetDir, &WRAP_DBSetDir },
	{ "DBMkDir", dissectio_DBMkDir, &WRAP_DBMkDir },
	{ "DBCpDir", dissectio_DBCpDir, &WRAP_DBCpDir },
	{ "DBGuessHasFriendlyHDF5Names", dissectio_DBGuessHasFriendlyHDF5Names, &WRAP_DBGuessHasFriendlyHDF5Names },
	{ "DBInqVarExists", dissectio_DBInqVarExists, &WRAP_DBInqVarExists },
	{ "DBUninstall", dissectio_DBUninstall, &WRAP_DBUninstall },
	{ "DBFreeCompressionResources", dissectio_DBFreeCompressionResources, &WRAP_DBFreeCompressionResources },
	{ "DBSortObjectsByOffset", dissectio_DBSortObjectsByOffset, &WRAP_DBSortObjectsByOffset },
	{ "DBFilters", dissectio_DBFilters, &WRAP_DBFilters },
	{ "DBInqFileHasObjects", dissectio_DBInqFileHasObjects, &WRAP_DBInqFileHasObjects },
	{ "DBAllocCompoundarray", dissectio_DBAllocCompoundarray, &WRAP_DBAllocCompoundarray },
	{ "DBAllocCurve", dissectio_DBAllocCurve, &WRAP_DBAllocCurve },
	{ "DBAllocDefvars", dissectio_DBAllocDefvars, &WRAP_DBAllocDefvars },
	{ "DBAllocMultimesh", dissectio_DBAllocMultimesh, &WRAP_DBAllocMultimesh },
	{ "DBAllocMultimeshadj", dissectio_DBAllocMultimeshadj, &WRAP_DBAllocMultimeshadj },
	{ "DBAllocMultivar", dissectio_DBAllocMultivar, &WRAP_DBAllocMultivar },
	{ "DBAllocMultimat", dissectio_DBAllocMultimat, &WRAP_DBAllocMultimat },
	{ "DBAllocMultimatspecies", dissectio_DBAllocMultimatspecies, &WRAP_DBAllocMultimatspecies },
	{ "DBAllocCsgmesh", dissectio_DBAllocCsgmesh, &WRAP_DBAllocCsgmesh },
	{ "DBAllocQuadmesh", dissectio_DBAllocQuadmesh, &WRAP_DBAllocQuadmesh },
	{ "DBAllocPointmesh", dissectio_DBAllocPointmesh, &WRAP_DBAllocPointmesh },
	{ "DBAllocMeshvar", dissectio_DBAllocMeshvar, &WRAP_DBAllocMeshvar },
	{ "DBAllocUcdmesh", dissectio_DBAllocUcdmesh, &WRAP_DBAllocUcdmesh },
	{ "DBAllocCsgvar", dissectio_DBAllocCsgvar, &WRAP_DBAllocCsgvar },
	{ "DBAllocQuadvar", dissectio_DBAllocQuadvar, &WRAP_DBAllocQuadvar },
	{ "DBAllocUcdvar", dissectio_DBAllocUcdvar, &WRAP_DBAllocUcdvar },
	{ "DBAllocZonelist", dissectio_DBAllocZonelist, &WRAP_DBAllocZonelist },
	{ "DBAllocPHZonelist", dissectio_DBAllocPHZonelist, &WRAP_DBAllocPHZonelist },
	{ "DBAllocCSGZonelist", dissectio_DBAllocCSGZonelist, &WRAP_DBAllocCSGZonelist },
	{ "DBAllocEdgelist", dissectio_DBAllocEdgelist, &WRAP_DBAllocEdgelist },
	{ "DBAllocFacelist", dissectio_DBAllocFacelist, &WRAP_DBAllocFacelist },
	{ "DBAllocMaterial", dissectio_DBAllocMaterial, &WRAP_DBAllocMaterial },
	{ "DBAllocMatspecies", dissectio_DBAllocMatspecies, &WRAP_DBAllocMatspecies },
	{ "DBAllocNamescheme", dissectio_DBAllocNamescheme, &WRAP_DBAllocNamescheme },
	{ "DBAllocGroupelmap", dissectio_DBAllocGroupelmap, &WRAP_DBAllocGroupelmap },
	{ "DBFreeMatspecies", dissectio_DBFreeMatspecies, &WRAP_DBFreeMatspecies },
	{ "DBFreeMaterial", dissectio_DBFreeMaterial, &WRAP_DBFreeMaterial },
	{ "DBFreeFacelist", dissectio_DBFreeFacelist, &WRAP_DBFreeFacelist },
	{ "DBFreeEdgelist", dissectio_DBFreeEdgelist, &WRAP_DBFreeEdgelist },
	{ "DBFreeZonelist", dissectio_DBFreeZonelist, &WRAP_DBFreeZonelist },
	{ "DBFreePHZonelist", dissectio_DBFreePHZonelist, &WRAP_DBFreePHZonelist },
	{ "DBFreeCSGZonelist", dissectio_DBFreeCSGZonelist, &WRAP_DBFreeCSGZonelist },
	{ "DBResetUcdvar", dissectio_DBResetUcdvar, &WRAP_DBResetUcdvar },
	{ "DBFreeUcdvar", dissectio_DBFreeUcdvar, &WRAP_DBFreeUcdvar },
	{ "DBResetQuadvar", dissectio_DBResetQuadvar, &WRAP_DBResetQuadvar },
	{ "DBFreeCsgvar", dissectio_DBFreeCsgvar, &WRAP_DBFreeCsgvar },
	{ "DBFreeQuadvar", dissectio_DBFreeQuadvar, &WRAP_DBFreeQuadvar },
	{ "DBFreeUcdmesh", dissectio_DBFreeUcdmesh, &WRAP_DBFreeUcdmesh },
	{ "DBFreeMeshvar", dissectio_DBFreeMeshvar, &WRAP_DBFreeMeshvar },
	{ "DBFreePointvar", dissectio_DBFreePointvar, &WRAP_DBFreePointvar },
	{ "DBFreePointmesh", dissectio_DBFreePointmesh, &WRAP_DBFreePointmesh },
	{ "DBFreeQuadmesh", dissectio_DBFreeQuadmesh, &WRAP_DBFreeQuadmesh },
	{ "DBFreeCsgmesh", dissectio_DBFreeCsgmesh, &WRAP_DBFreeCsgmesh },
	{ "DBFreeDefvars", dissectio_DBFreeDefvars, &WRAP_DBFreeDefvars },
	{ "DBFreeMultimesh", dissectio_DBFreeMultimesh, &WRAP_DBFreeMultimesh },
	{ "DBFreeMultimeshadj", dissectio_DBFreeMultimeshadj, &WRAP_DBFreeMultimeshadj },
	{ "DBFreeMultivar", dissectio_DBFreeMultivar, &WRAP_DBFreeMultivar },
	{ "DBFreeMultimat", dissectio_DBFreeMultimat, &WRAP_DBFreeMultimat },
	{ "DBFreeMultimatspecies", dissectio_DBFreeMultimatspecies, &WRAP_DBFreeMultimatspecies },
	{ "DBFreeCompoundarray", dissectio_DBFreeCompoundarray, &WRAP_DBFreeCompoundarray },
	{ "DBFreeCurve", dissectio_DBFreeCurve, &WRAP_DBFreeCurve },
	{ "DBFreeNamescheme", dissectio_DBFreeNamescheme, &WRAP_DBFreeNamescheme },
	{ "DBFreeMrgvar", dissectio_DBFreeMrgvar, &WRAP_DBFreeMrgvar },
	{ "DBFreeMrgtree", dissectio_DBFreeMrgtree, &WRAP_DBFreeMrgtree },
	{ "DBFreeGroupelmap", dissectio_DBFreeGroupelmap, &WRAP_DBFreeGroupelmap },
	{ "DBIsEmptyCurve", dissectio_DBIsEmptyCurve, &WRAP_DBIsEmptyCurve },
	{ "DBIsEmptyPointmesh", dissectio_DBIsEmptyPointmesh, &WRAP_DBIsEmptyPointmesh },
	{ "DBIsEmptyPointvar", dissectio_DBIsEmptyPointvar, &WRAP_DBIsEmptyPointvar },
	{ "DBIsEmptyMeshvar", dissectio_DBIsEmptyMeshvar, &WRAP_DBIsEmptyMeshvar },
	{ "DBIsEmptyQuadmesh", dissectio_DBIsEmptyQuadmesh, &WRAP_DBIsEmptyQuadmesh },
	{ "DBIsEmptyQuadvar", dissectio_DBIsEmptyQuadvar, &WRAP_DBIsEmptyQuadvar },
	{ "DBIsEmptyUcdmesh", dissectio_DBIsEmptyUcdmesh, &WRAP_DBIsEmptyUcdmesh },
	{ "DBIsEmptyFacelist", dissectio_DBIsEmptyFacelist, &WRAP_DBIsEmptyFacelist },
	{ "DBIsEmptyZonelist", dissectio_DBIsEmptyZonelist, &WRAP_DBIsEmptyZonelist },
	{ "DBIsEmptyPHZonelist", dissectio_DBIsEmptyPHZonelist, &WRAP_DBIsEmptyPHZonelist },
	{ "DBIsEmptyUcdvar", dissectio_DBIsEmptyUcdvar, &WRAP_DBIsEmptyUcdvar },
	{ "DBIsEmptyCsgmesh", dissectio_DBIsEmptyCsgmesh, &WRAP_DBIsEmptyCsgmesh },
	{ "DBIsEmptyCSGZonelist", dissectio_DBIsEmptyCSGZonelist, &WRAP_DBIsEmptyCSGZonelist },
	{ "DBIsEmptyCsgvar", dissectio_DBIsEmptyCsgvar, &WRAP_DBIsEmptyCsgvar },
	{ "DBIsEmptyMaterial", dissectio_DBIsEmptyMaterial, &WRAP_DBIsEmptyMaterial },
	{ "DBIsEmptyMatspecies", dissectio_DBIsEmptyMatspecies, &WRAP_DBIsEmptyMatspecies },
	{ "DBGetObjtypeTag", dissectio_DBGetObjtypeTag, &WRAP_DBGetObjtypeTag },
	{ "DBMakeObject", dissectio_DBMakeObject, &WRAP_DBMakeObject },
	{ "DBFreeObject", dissectio_DBFreeObject, &WRAP_DBFreeObject },
	{ "DBClearObject", dissectio_DBClearObject, &WRAP_DBClearObject },
	{ "DBAddVarComponent", dissectio_DBAddVarComponent, &WRAP_DBAddVarComponent },
	{ "DBAddIntComponent", dissectio_DBAddIntComponent, &WRAP_DBAddIntComponent },
	{ "DBAddFltComponent", dissectio_DBAddFltComponent, &WRAP_DBAddFltComponent },
	{ "DBAddDblComponent", dissectio_DBAddDblComponent, &WRAP_DBAddDblComponent },
	{ "DBAddStrComponent", dissectio_DBAddStrComponent, &WRAP_DBAddStrComponent },
	{ "DBGetComponentNames", dissectio_DBGetComponentNames, &WRAP_DBGetComponentNames },
	{ "DBGetObject", dissectio_DBGetObject, &WRAP_DBGetObject },
	{ "DBChangeObject", dissectio_DBChangeObject, &WRAP_DBChangeObject },
	{ "DBWriteObject", dissectio_DBWriteObject, &WRAP_DBWriteObject },
	{ "DBGetComponent", dissectio_DBGetComponent, &WRAP_DBGetComponent },
	{ "DBGetComponentType", dissectio_DBGetComponentType, &WRAP_DBGetComponentType },
	{ "DBWriteComponent", dissectio_DBWriteComponent, &WRAP_DBWriteComponent },
	{ "DBWrite", dissectio_DBWrite, &WRAP_DBWrite },
	{ "DBWriteSlice", dissectio_DBWriteSlice, &WRAP_DBWriteSlice },
	{ "DBRead", dissectio_DBRead, &WRAP_DBRead },
	{ "DBReadVar", dissectio_DBReadVar, &WRAP_DBReadVar },
	{ "DBReadVarSlice", dissectio_DBReadVarSlice, &WRAP_DBReadVarSlice },
	{ "DBGetCompoundarray", dissectio_DBGetCompoundarray, &WRAP_DBGetCompoundarray },
	{ "DBInqCompoundarray", dissectio_DBInqCompoundarray, &WRAP_DBInqCompoundarray },
	{ "DBGetVar", dissectio_DBGetVar, &WRAP_DBGetVar },
	{ "DBGetVarByteLength", dissectio_DBGetVarByteLength, &WRAP_DBGetVarByteLength },
	{ "DBGetVarLength", dissectio_DBGetVarLength, &WRAP_DBGetVarLength },
	{ "DBGetVarDims", dissectio_DBGetVarDims, &WRAP_DBGetVarDims },
	{ "DBGetVarType", dissectio_DBGetVarType, &WRAP_DBGetVarType },
	{ "DBInqVarType", dissectio_DBInqVarType, &WRAP_DBInqVarType },
	{ "DBGetCurve", dissectio_DBGetCurve, &WRAP_DBGetCurve },
	{ "DBGetDefvars", dissectio_DBGetDefvars, &WRAP_DBGetDefvars },
	{ "DBGetMaterial", dissectio_DBGetMaterial, &WRAP_DBGetMaterial },
	{ "DBGetMatspecies", dissectio_DBGetMatspecies, &WRAP_DBGetMatspecies },
	{ "DBGetPointmesh", dissectio_DBGetPointmesh, &WRAP_DBGetPointmesh },
	{ "DBGetPointvar", dissectio_DBGetPointvar, &WRAP_DBGetPointvar },
	{ "DBGetQuadmesh", dissectio_DBGetQuadmesh, &WRAP_DBGetQuadmesh },
	{ "DBGetQuadvar", dissectio_DBGetQuadvar, &WRAP_DBGetQuadvar },
	{ "DBGetUcdmesh", dissectio_DBGetUcdmesh, &WRAP_DBGetUcdmesh },
	{ "DBGetUcdvar", dissectio_DBGetUcdvar, &WRAP_DBGetUcdvar },
	{ "DBGetCsgmesh", dissectio_DBGetCsgmesh, &WRAP_DBGetCsgmesh },
	{ "DBGetCsgvar", dissectio_DBGetCsgvar, &WRAP_DBGetCsgvar },
	{ "DBGetCSGZonelist", dissectio_DBGetCSGZonelist, &WRAP_DBGetCSGZonelist },
	{ "DBGetFacelist", dissectio_DBGetFacelist, &WRAP_DBGetFacelist },
	{ "DBGetZonelist", dissectio_DBGetZonelist, &WRAP_DBGetZonelist },
	{ "DBGetPHZonelist", dissectio_DBGetPHZonelist, &WRAP_DBGetPHZonelist },
	{ "DBInqMeshname", dissectio_DBInqMeshname, &WRAP_DBInqMeshname },
	{ "DBInqMeshtype", dissectio_DBInqMeshtype, &WRAP_DBInqMeshtype },
	{ "DBPutCompoundarray", dissectio_DBPutCompoundarray, &WRAP_DBPutCompoundarray },
	{ "DBPutCurve", dissectio_DBPutCurve, &WRAP_DBPutCurve },
	{ "DBPutDefvars", dissectio_DBPutDefvars, &WRAP_DBPutDefvars },
	{ "DBPutFacelist", dissectio_DBPutFacelist, &WRAP_DBPutFacelist },
	{ "DBPutMaterial", dissectio_DBPutMaterial, &WRAP_DBPutMaterial },
	{ "DBPutMatspecies", dissectio_DBPutMatspecies, &WRAP_DBPutMatspecies },
	{ "DBPutPointmesh", dissectio_DBPutPointmesh, &WRAP_DBPutPointmesh },
	{ "DBPutPointvar", dissectio_DBPutPointvar, &WRAP_DBPutPointvar },
	{ "DBPutPointvar1", dissectio_DBPutPointvar1, &WRAP_DBPutPointvar1 },
	{ "DBPutQuadmesh", dissectio_DBPutQuadmesh, &WRAP_DBPutQuadmesh },
	{ "DBPutQuadvar", dissectio_DBPutQuadvar, &WRAP_DBPutQuadvar },
	{ "DBPutQuadvar1", dissectio_DBPutQuadvar1, &WRAP_DBPutQuadvar1 },
	{ "DBPutUcdmesh", dissectio_DBPutUcdmesh, &WRAP_DBPutUcdmesh },
	{ "DBPutUcdsubmesh", dissectio_DBPutUcdsubmesh, &WRAP_DBPutUcdsubmesh },
	{ "DBPutUcdvar", dissectio_DBPutUcdvar, &WRAP_DBPutUcdvar },
	{ "DBPutUcdvar1", dissectio_DBPutUcdvar1, &WRAP_DBPutUcdvar1 },
	{ "DBPutZonelist", dissectio_DBPutZonelist, &WRAP_DBPutZonelist },
	{ "DBPutZonelist2", dissectio_DBPutZonelist2, &WRAP_DBPutZonelist2 },
	{ "DBPutPHZonelist", dissectio_DBPutPHZonelist, &WRAP_DBPutPHZonelist },
	{ "DBPutCsgmesh", dissectio_DBPutCsgmesh, &WRAP_DBPutCsgmesh },
	{ "DBPutCSGZonelist", dissectio_DBPutCSGZonelist, &WRAP_DBPutCSGZonelist },
	{ "DBPutCsgvar", dissectio_DBPutCsgvar, &WRAP_DBPutCsgvar },
	{ "DBPrintMrgtree", dissectio_DBPrintMrgtree, &WRAP_DBPrintMrgtree },
	{ "DBLinearizeMrgtree", dissectio_DBLinearizeMrgtree, &WRAP_DBLinearizeMrgtree },
	{ "DBWalkMrgtree", dissectio_DBWalkMrgtree, &WRAP_DBWalkMrgtree },
	{ "DBMakeMrgtree", dissectio_DBMakeMrgtree, &WRAP_DBMakeMrgtree },
	{ "DBAddRegion", dissectio_DBAddRegion, &WRAP_DBAddRegion },
	{ "DBAddRegionArray", dissectio_DBAddRegionArray, &WRAP_DBAddRegionArray },
	{ "DBSetCwr", dissectio_DBSetCwr, &WRAP_DBSetCwr },
	{ "DBGetCwr", dissectio_DBGetCwr, &WRAP_DBGetCwr },
	{ "DBPutMrgtree", dissectio_DBPutMrgtree, &WRAP_DBPutMrgtree },
	{ "DBPutMrgvar", dissectio_DBPutMrgvar, &WRAP_DBPutMrgvar },
	{ "DBPutGroupelmap", dissectio_DBPutGroupelmap, &WRAP_DBPutGroupelmap },
	{ "DBGetMrgvar", dissectio_DBGetMrgvar, &WRAP_DBGetMrgvar },
	{ "DBGetName", dissectio_DBGetName, &WRAP_DBGetName },
	{ "DBGetMultimesh", dissectio_DBGetMultimesh, &WRAP_DBGetMultimesh },
	{ "DBGetMultimeshadj", dissectio_DBGetMultimeshadj, &WRAP_DBGetMultimeshadj },
	{ "DBGetMultivar", dissectio_DBGetMultivar, &WRAP_DBGetMultivar },
	{ "DBGetMultimat", dissectio_DBGetMultimat, &WRAP_DBGetMultimat },
	{ "DBGetMultimatspecies", dissectio_DBGetMultimatspecies, &WRAP_DBGetMultimatspecies },
	{ "DBPutMultimesh", dissectio_DBPutMultimesh, &WRAP_DBPutMultimesh },
	{ "DBPutMultimeshadj", dissectio_DBPutMultimeshadj, &WRAP_DBPutMultimeshadj },
	{ "DBPutMultivar", dissectio_DBPutMultivar, &WRAP_DBPutMultivar },
	{ "DBPutMultimat", dissectio_DBPutMultimat, &WRAP_DBPutMultimat },
	{ "DBPutMultimatspecies", dissectio_DBPutMultimatspecies, &WRAP_DBPutMultimatspecies },
	{ "DBMakeOptlist", dissectio_DBMakeOptlist, &WRAP_DBMakeOptlist },
	{ "DBClearOptlist", dissectio_DBClearOptlist, &WRAP_DBClearOptlist },
	{ "DBFreeOptlist", dissectio_DBFreeOptlist, &WRAP_DBFreeOptlist },
	{ "DBAddOption", dissectio_DBAddOption, &WRAP_DBAddOption },
	{ "DBGetOption", dissectio_DBGetOption, &WRAP_DBGetOption },
	{ "DBClearOption", dissectio_DBClearOption, &WRAP_DBClearOption },
	{ "DBAnnotateUcdmesh", dissectio_DBAnnotateUcdmesh, &WRAP_DBAnnotateUcdmesh },
	{ "DBCalcExternalFacelist", dissectio_DBCalcExternalFacelist, &WRAP_DBCalcExternalFacelist },
	{ "DBCalcExternalFacelist2", dissectio_DBCalcExternalFacelist2, &WRAP_DBCalcExternalFacelist2 },
	{ "DBJoinPath", dissectio_DBJoinPath, &WRAP_DBJoinPath },
	{ "DBStringArrayToStringList", dissectio_DBStringArrayToStringList, &WRAP_DBStringArrayToStringList },
	{ "DBStringListToStringArray", dissectio_DBStringListToStringArray, &WRAP_DBStringListToStringArray },
	{ "DBIsDifferentDouble", dissectio_DBIsDifferentDouble, &WRAP_DBIsDifferentDouble },
	{ "DBIsDifferentLongLong", dissectio_DBIsDifferentLongLong, &WRAP_DBIsDifferentLongLong },
	{ "DBFortranAccessPointer", dissectio_DBFortranAccessPointer, &WRAP_DBFortranAccessPointer },
	{ "DBFortranAllocPointer", dissectio_DBFortranAllocPointer, &WRAP_DBFortranAllocPointer },
	{ "DBFortranRemovePointer", dissectio_DBFortranRemovePointer, &WRAP_DBFortranRemovePointer },
	{ "_db_safe_strdup", dissectio__db_safe_strdup, &WRAP__db_safe_strdup },
};

void init_gotcha_all_silo () {
	gotcha_wrap(wrap_all_silo, NFUNCS, "dissectio");
}
